### ISSUE TITLE
请求一个YUV问题

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#10]
我用的surfaceview 从onpreviewframe 里面得到 YUV 数据 怎么进行缩放啊

**Comment by flyminiboy** [comment]
还有一个问题就是 预览变形这个问题你是怎么处理的啊？

**Comment by lakeinchina** [comment]
预览变形把textureview大小调成视频比例就行了呗,改onmeasure.在prepare之后可以通过getVideoSize来获取视频大小.
"我用的surfaceview 从onpreviewframe 里面得到 YUV 数据 怎么进行缩放啊"和这个库没关系吧?不知道你是要缩放来显示还是编码?

**Comment by flyminiboy** [comment]
我surfaceview是全屏的固定大小的

**Comment by lakeinchina** [comment]
surfaceview调成不是全屏固定大小

**Comment by flyminiboy** [comment]
还有没有其他的解决办法，调成不固定估计产品不同意。别的直播软件也都是全屏啊 也没有发现他们变形啊

**Comment by lakeinchina** [comment]
surfaceview调成视频比例。。超出屏幕大。这就是一个纯排版的问题，一个正方形视频在长方形屏幕上怎么显示？要么拉伸要么留黑边要么让视频超出屏幕一部分
就是计算屏幕大小和视频大小来调整surfaceview大小，让surfaceview超出屏幕大，视频有一部分边缘看不到

**Comment by flyminiboy** [comment]
设置一个大尺寸 预览的画面也放大了

**Comment by lakeinchina** [comment]
把一个imageview设成FitXY，如何设置这个imageview的大小来让图片不变形的全屏显示在屏幕上，横向被压缩了就把width设大，横向被拉伸了就把height设大，这就是一个UI排版问题，不在推流讨论的问题范围内.
其他直播软件都是通过设置surfaceview大小来处理的，要不然不可能适配所有屏幕，还包括vlc，ijk播放器也是一样方法来手动设置4:3,16:9
