### ISSUE TITLE
预览画面局部地区黑屏

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#100]
![test](https://cloud.githubusercontent.com/assets/8833677/20128668/b5c8e5b0-a684-11e6-9bb9-8a02f9ac28f7.jpeg)

OPPO vivo 出现这个问题比较多
vivo x3
华为有偶现

**Comment by lakeinchina** [comment]
这是美颜的问题

**Comment by flyminiboy** [comment]
有什么解决的方法吗？

**Comment by lakeinchina** [comment]
偶现的话，不太好查，有什么出现的特征么？我没有遇到过，是hard模式skinblur滤镜？

**Comment by flyminiboy** [comment]
部分机型算是必现吧  vivo x3 应该算是必现了。是hard模式磨皮和美白俩个滤镜组合的

**Comment by flyminiboy** [comment]
应该是磨皮的问题，我把磨皮的滤镜屏蔽掉以后。测试没有出现问题

**Comment by flyminiboy** [comment]
磨皮那一块有什么好的改进的办法吗？

**Comment by flyminiboy** [comment]
现在磨皮是采用的高斯模糊的，如果换成双边滤波的会不会好点呢

**Comment by flyminiboy** [comment]
在 OriginalVideoFilter -> onDraw 里面进行了修改
GLES20.glClearColor(1.0f, 1.0f, 1.0f, 0.0f);
GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT | GLES20.GL_DEPTH_BUFFER_BIT);
然后我这边测试貌似没有了问题

**Comment by lakeinchina** [comment]
@fly518420 我没那个测试机，你可以试下在初始化gl的时候glDisable(GLES20.GL_DEPTH_TEST)一下，看看是不是能解决问题，可能是个兼容性的bug吧
