### ISSUE TITLE
Set view fullscreen

### ISSUE THREAD

**Issue by HuuThang91** [lakeinchina/librestreaming#102]
How can i set view fullscreen with targetvideoSize 720x480

**Comment by lakeinchina** [comment]
set the AspectTextureView full screen and setAspectRatio(AspectTextureView.MODE_OUTSIDE

**Comment by HuuThang91** [comment]
Hi lakeinchina, thanks to response so quickly. i try to set setAspectRatio(AspectTextureView.MODE_OUTSIDE,ratio) with ratio is a widthscreen/heightscreen .But nothing happen, what should i do?

**Comment by lakeinchina** [comment]
are you using the sample?

**Comment by HuuThang91** [comment]
yes, my configuration like sample app and txv_preview is full screen. But the blank space still exists with target video size 720 480. Here is my config
  txv_preview = (AspectTextureView) findViewById(R.id.txv_preview);
        txv_preview.setAspectRatio(AspectTextureView.MODE_OUTSIDE,ratio);
//        txv_preview.setKeepScreenOn(true);
        txv_preview.setSurfaceTextureListener(this);
        txv_preview.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                heartView.add();
            }
        });
        resClient = new RESClient();
        resConfig = RESConfig.obtain();
        resConfig.setFilterMode(filtermode);
        resConfig.setTargetVideoSize(new Size(720, 480));
        resConfig.setBitRate(1000 \* 1024);
        resConfig.setVideoFPS(25);
        resConfig.setRenderingMode(RESConfig.RenderingMode.OpenGLES);
        resConfig.setDefaultCamera(Camera.CameraInfo.CAMERA_FACING_FRONT);

**Comment by HuuThang91** [comment]
thank lake in china for supportting. i just change onMeasure in your lib and its solve my problem.

**Comment by HuuThang91** [comment]
another question, how can i change header ( sps,pps) of h264 stream . Its seem like my server receive the stream but can't decode  that stream .

**Comment by lakeinchina** [comment]
[Packager.java](https://github.com/lakeinchina/librestreaming/blob/master/librestreaming/src/main/java/me/lake/librestreaming/core/Packager.java)

**Comment by HuuThang91** [comment]
i dont know why, my stream send to rtmp server ( using elemental hardware encoder) .And server cant encode that stream . Can you  please help me .

**Comment by HuuThang91** [comment]
INFO:   width                 480.00
INFO:   height                720.00
INFO:   displayWidth          480.00
INFO:   displayHeight         720.00
INFO:   duration              0.00
INFO:   framerate             10.00
INFO:   fps                   10.00
INFO:   videodatarate         0.00
INFO:   videocodecid          7.00
INFO:   audiodatarate         32.00
INFO:   audiocodecid          10.00
INFO:   profile
INFO:   level
info i get from my own server ,  profile and level is blank.May be that why elemental hardware encoder cant decore . Please help me fix it

**Comment by lakeinchina** [comment]
it`s metadata, it is useless for encoder.it should be ok even without it.
but if you want to change it you can try [FLvMetaData.java](https://github.com/lakeinchina/librestreaming/blob/master/librestreaming/src/main/java/me/lake/librestreaming/rtmp/FLvMetaData.java)

which server are you using?it should be ok on srs,ngnix-rtmp, wowza server

**Comment by HuuThang91** [comment]
im  using server elemental live from elemental company  , how about rmtp protocols, is there any method should i emplement

**Comment by lakeinchina** [comment]
it using librtmp which implemented rtmp protocol.
may be server elemental live has some special requirement.

**Comment by HuuThang91** [comment]
one more question :) , can i change video output H264 Baseline 3.1 H264 Baseline 4.0 and how can i do it :)

**Comment by lakeinchina** [comment]
change ‘videoFormat.setInteger(MediaFormat.KEY_LEVEL, MediaCodecInfo.CodecProfileLevel.AVCLevel31);’ in MediaCodecHelper.java.
but it may be useless because of system problem.

**Comment by HuuThang91** [comment]
my server (still alive) is rtmp://123.29.67.66/live/kenh9 , and link CDN to play in VLC is http://cdn1.ceeme.vn/live.m3u8?c=vstv1008&q=auto&proaudio=high,medium,250k&pkg=pkg0&type=live&rkey=e70f21fc20fa7ffd05b1df1e5ee96836&userId=ceme&deviceId=ceme&loc=hni&zn=net&st=&et=

Can you please check it for me, i am stuck in it for a weeks, and i really dont know how to fix it.

**Comment by lakeinchina** [comment]
I'll try to check it next week.

**Comment by HuuThang91** [comment]
thanks a lot :)

**Comment by lakeinchina** [comment]
this cdn link is 404.maybe you can catch some error log by playing with ffplay.

**Comment by RazmigPapissian** [comment]
@HuuThang91 what did you change in onMeasure to get rid of the blank space?
