### ISSUE TITLE
Any plan to support x86 device?

### ISSUE THREAD

**Issue by jutikorn** [lakeinchina/librestreaming#103]
App can't be run on the x86 device. Do you have any plan to support it?

**Comment by lakeinchina** [comment]
sorry,no plan to support,I even don`t have any x86 devices

**Comment by jutikorn** [comment]
@lakeinchina you can actually use emulator or genymotion https://www.genymotion.com/
to test on the x86 enviroment.

**Comment by lakeinchina** [comment]
emulator can`t simulate camera and microphone , especially Hardware Encoder.
