### ISSUE TITLE
生成的x86、arm64的so库直播停止时崩溃

### ISSUE THREAD

**Issue by skybdemq** [lakeinchina/librestreaming#104]
Hi
我编译生成的arm64的so库在荣耀畅玩4X直播停止调用stopStreaming方法崩溃，跟踪发现执行到RESRtmpSender类final int closeR = RtmpClient.close(jniRtmpPointer);这句就崩了。
x86的so库在小米平板2同样调用stopStreaming崩溃。
但是测试了sample就没问题。
如果用armv7a就都没问题不崩溃。

请问清楚什么原因吗？怎样生成好的arm64、x86版本的so库？
我看了#71，情况是一样样的

**Comment by lakeinchina** [comment]
不生成arm64的库直接用armv7就没问题，x86设备太少了而且我一台也没有，所以没有计划去支持。
