### ISSUE TITLE
采样分辨率很低的时候，边缘会有锯齿出现。

### ISSUE THREAD

**Issue by IsaiahKing** [lakeinchina/librestreaming#107]
在尝试使用640*360分辨率采集视频时，边缘会有很明显的锯齿出现。
我尝试使用了4x MSAA消除锯齿。好像，并没有什么效果。
这个有什么好的解决方法么。

**Comment by lakeinchina** [comment]
你说的是播放的时候有锯齿吗？

**Comment by IsaiahKing** [comment]
预览和拉流端都会有，颜色差异比较大，并且具有一定宽度的边缘特别明显。

**Comment by lakeinchina** [comment]
我只发现在ffplay播放的时候如果拉伸画面会有锯齿，预览没有发现。
