### ISSUE TITLE
直播推流画面推流的抖动画面会花屏？

### ISSUE THREAD

**Issue by snube** [lakeinchina/librestreaming#11]
这个问题有什么办法解决？推流上去后晃动手机接收端看起来画面会很花

**Comment by lakeinchina** [comment]
1，调高码率
2，调小关键帧间隔（MediaFormat.KEY_I_FRAME_INTERVAL）
3，把AVCprofile设成Main，但是我把这块代码注视掉了，因为在某些环境中会导致一些问题，我还没有确定是什么bug
这个和手机编码器的好坏有很大关系

**Comment by lakeinchina** [comment]
profile设Main的问题找到了，交错编码的问题，后面会改掉

**Comment by snube** [comment]
好的，谢谢，我去试试。

**Comment by js-zh** [comment]
请问如何控制帧率？

**Comment by ghost** [comment]
How to play videos from my phone instead of the camera




Kind regards,
Vishal Gupta <https://www.linkedin.com/in/vishalgupta0203/>

**Comment by ghost** [comment]
如何从我的手机而不是相机播放视频

Rúhé cóng wǒ de shǒujī ér bùshì xiàngjī bòfàng shìpín



Kind regards,
Vishal Gupta <https://www.linkedin.com/in/vishalgupta0203/>
