### ISSUE TITLE
马赛克

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#112]
推流的时候 来回晃动设备，观看的时候画面马赛克，除了提高码率还有其他可以进行优化的方式吗？

**Comment by lakeinchina** [comment]
可以用MediaFormat.KEY_BITRATE_MODE的BITRATE_MODE_CQ固定质量动态码率如果设备支持的话，但是这样就不能根据网速调整码率了

**Comment by flyminiboy** [comment]
改了以后好像还是不行。感觉效果和iOS那种不一样，感觉iOS那种抖动是瞬间的，但是现在Android是缓慢的移动，然后就有了马赛克

**Comment by lakeinchina** [comment]
你可以确认下是否画面运动的时候码率升高了。。
瞬间抖动说明没防抖。缓慢移动说明有防抖。
有马赛克这种问题没办法解决，ios硬编码能录main，high，安卓只能baseline，同样码率baseline不可能比main好，你要是想解决马赛克又不想升码率，那就只能用ffmpegx264去录main编码的视频

**Comment by flyminiboy** [comment]
防抖是可以控制的吗？
profile 这个我看Android可以获取到当前设备支持的列表，但是有的设置不生效。

**Comment by fly518420** [comment]
防抖是可以控制的吗？
profile 这个我看Android可以获取到当前设备支持的列表，但是有的设置不生效。

**Comment by fly518420** [comment]
防抖是可以控制的吗？
profile 这个我看Android可以获取到当前设备支持的列表，但是有的设置不生效。

**Comment by lakeinchina** [comment]
profile和level都能获取，但是大部分手机都不生效

**Comment by frendyxzc** [comment]
@fly518420 您好，打扰了，请问 移动时马赛克 的问题，有修改解决吗？
