### ISSUE TITLE
软件编码的问题

### ISSUE THREAD

**Issue by JakeRed** [lakeinchina/librestreaming#113]
软件编码在demo中能支持时间戳吗？目前没找到。

**Comment by lakeinchina** [comment]
你的时间戳指的是什么？软模式指的是cpu滤镜，不是软编码

**Comment by JakeRed** [comment]
我是说软模式的滤镜里没有TimeStamp，我想软模式也应该有一个显示时间的地方。

**Comment by lakeinchina** [comment]
哦，你是说sample里面软模式没有Timestamp滤镜吧。这些滤镜都是示例用的，我没给软模式写这个滤镜，你有自己需要可以参考IconFilterSoft和TextHardFilter去写滤镜
