### ISSUE TITLE
视频录制怎样压缩体积

### ISSUE THREAD

**Issue by skybdemq** [lakeinchina/librestreaming#114]
HI
请教个问题，我用mediamuxer录制视频，但录制出的视频体积有些大，请问有什么方法能使用录制视频体积小点呢

**Comment by lakeinchina** [comment]
这个如果用安卓原生的硬件编码器，基本没有什么好优化的空间，因为只能录baseline，要么降低码率，帧率，要么用动态码率功能（如果设备支持的话）

**Comment by skybdemq** [comment]
嗯，码率、帧率降低一点差别不大，又要保证清晰度不能降太多。我试过录制完成后生成mp4再用ffmpeg去压缩，但是速度奇慢

**Comment by lakeinchina** [comment]
ffmpeg去压缩是会很慢，如果不想后期再次转换，又对视频体积要求高的话，那只能放弃硬件编码器，在录制的时候就用软编了
