### ISSUE TITLE
SkinBlurHardVideoFilter无效或崩溃

### ISSUE THREAD

**Issue by skybdemq** [lakeinchina/librestreaming#115]
HI，librestreaming
在小米4和一加1设置滤镜SkinBlurHardVideoFilter没效果，小米note2崩溃

**Comment by skybdemq** [comment]
编译运行sample测试，也是一样，请问知道是什么问题吗，怎样处理？

**Comment by skybdemq** [comment]
我先选SeaScapeFilter，再选SkinBlurHardVideoFilter就有效果

**Comment by lakeinchina** [comment]
我不太清楚这个神奇问题是怎么回事。。崩溃的哪个有log吗

**Comment by skybdemq** [comment]
崩溃打印的log：
12-23 10:58:26.544 26743-26743/? I/art: Late-enabling -Xcheck:jni
12-23 10:58:26.544 26743-26743/? D/houdini: [26743] Initialize library(version: 5.2.2b_y.47801 RELEASE)... successfully.
12-23 10:58:26.654 26743-26743/me.lake.librestreaming.sample W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-23 10:58:26.758 26743-26773/me.lake.librestreaming.sample D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-23 10:58:26.765 26743-26743/me.lake.librestreaming.sample D/ActivityThreadInjector: clearCachedDrawables.
12-23 10:58:26.804 26743-26773/me.lake.librestreaming.sample D/ufoEGL: ENV OGL (32bit) enabled for all processes, use "setptop persist.intel.ogl.procname" to limit it to a single process
12-23 10:58:26.810 26743-26773/me.lake.librestreaming.sample I/ufoGralloc: Hello, this is UFO GRALLOC/Intel Corporation
12-23 10:58:26.812 26743-26773/me.lake.librestreaming.sample I/OpenGLRenderer: Initialized EGL, version 1.4
12-23 10:58:26.813 26743-26773/me.lake.librestreaming.sample W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
12-23 10:58:26.813 26743-26773/me.lake.librestreaming.sample D/ufoEGL: droid_create_context : config id = 9 conf->NativeVisualID=1
12-23 10:58:26.813 26743-26773/me.lake.librestreaming.sample I/ufoEGL: Requested context : GLES 2.0
12-23 10:58:26.813 26743-26773/me.lake.librestreaming.sample D/ufoEGL: Pixel Format : GGL_PIXEL_FORMAT_RGBA_8888
12-23 10:58:26.820 26743-26773/me.lake.librestreaming.sample D/ufoEGL: Pixel Format : GGL_PIXEL_FORMAT_RGBA_8888
12-23 10:58:26.821 26743-26773/me.lake.librestreaming.sample D/OpenGLRenderer: Enabling debug mode 0
12-23 10:58:26.821 26743-26773/me.lake.librestreaming.sample D/ufoEGL: Pixel Format : GGL_PIXEL_FORMAT_RGBA_8888
12-23 10:58:26.823 26743-26773/me.lake.librestreaming.sample D/skuwa: Detected device 22B0:32 family 17:11
12-23 10:58:48.484 26743-26751/me.lake.librestreaming.sample I/art: Thread[5,tid=26751,WaitingInMainSignalCatcherLoop,Thread*=0xf383e200,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
12-23 10:58:48.566 26743-26751/me.lake.librestreaming.sample I/art: Wrote stack traces to '/data/anr/traces.txt'
12-23 10:59:26.497 26743-26743/me.lake.librestreaming.sample W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection

**Comment by skybdemq** [comment]
另外我试了将const mediump mat3 gaussianMap = mat3(0.145,0.131,0.104,0.131,0.122,0.096,0.104,0.096,0.075);
这段代码的值除了0.145，其他的改为2倍3倍，发现有效果，但感觉效果不好。
所以，其实不是无效，只是原来的效果不明显以为没效果
请教下，高斯模糊的参数值怎么计算得来的？
还有很奇怪选了SeaScapeFilter再SkinBlurHardVideoFilter，会加重其效果，gpu着色器缓存有关？

**Comment by lakeinchina** [comment]
是不是这两个手机摄像头本身就把图像给磨皮过了？

**Comment by skybdemq** [comment]
我打开相机看，并没有做任何处理

**Comment by lakeinchina** [comment]
我觉得有可能是不同手机shader浮点数精度的问题，你可以把SkinBklurHardVideoFilter 的shader里面几个mediump改称highp试一下

**Comment by skybdemq** [comment]
改成highp后有效果了
但是小米note2还是会崩溃
8780/me.lake.librestreaming.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x60 in tid 28780 (GLThread)

**Comment by lakeinchina** [comment]
这个log什么也看不出来，建议debug一下在哪个位置蹦的
