### ISSUE TITLE
Adaptive Streaming

### ISSUE THREAD

**Issue by developeralp** [lakeinchina/librestreaming#116]
Hello,

im starting live stream with 720x480 resolution and 750x1024 bitrate 

But live stream is lagging sometimes.(in wifi and mobile data )

How can i solve that ?
Is there are any solutions like adaptive streaming ? 

Or should i set bitrate to 500x1024 but i think 500 kbps will make video quality bad.

**Comment by lakeinchina** [comment]
you can use getSendBufferFreePercent() to get current network quality . 1.0f means good,0.0f means bad and start to drop packet.
so , check **getSendBufferFreePercent**() Repeatedly like one second.when it less than 1.0, use **reSetVideoBitrate** to set a smaller value. Similarly you can set a bigger value when it is 1.0f.
it has no Performance loss.
here is an example , you can take your own strategy.
```
int quality_value_min = 200 * 1024;
int quality_value_standard = 750 * 1024;
int quality_value_max = 1200 * 1024;
int curr = resClient.getVideoBitrate();
int target;
if (resClient.getSendBufferFreePercent() <= 0.8f) {//reduce bitrate
	if (resClient.getVideoBitrate() > quality_value_min) {
		target = (curr / 5 * 4) <= quality_value_min ? quality_value_min:(curr / 5 * 4);
		resClient.reSetVideoBitrate(target);
	}
} else {//raise bitrate
		if (resClient.getVideoBitrate() < quality_value_max) {
		target = (curr / 20 * 21) >= quality_value_max ? quality_value_max:(curr / 20 * 21);
		resClient.reSetVideoBitrate(target);
		}
	}
}
```
you can also change senderQueueLength in RESCoreParameters.it is the length of send buffer.larger means store more data when net block.

**Comment by developeralp** [comment]
Thanks lakeinchina , you are the best :)

**Comment by lakeinchina** [comment]
thanks a lot :)
