### ISSUE TITLE
请问可以设置镜像吗

### ISSUE THREAD

**Issue by huangsai** [lakeinchina/librestreaming#117]

**Comment by lakeinchina** [comment]
具体指的是预览还是推流？

**Comment by huangsai** [comment]
推流

**Comment by huangsai** [comment]
现在的预览是对的  但是观看的时候 应该左右颠倒一下

**Comment by lakeinchina** [comment]
GLHelper.java
hard模式
把MediaCodecTextureVertices[] = {
0.0f, 1.0f,
0.0f, 0.0f,
1.0f, 0.0f,
1.0f, 1.0f};
改成MediaCodecTextureVertices[] = {
1.0f, 1.0f,
1.0f, 0.0f,
0.0f, 0.0f,
0.0f, 1.0f};

**Comment by huangsai** [comment]
这样把后置摄像头也改了 怎么才可以只改前置摄像头 不改后置摄像头呢？

**Comment by huangsai** [comment]
这个问题可以解决吗？

**Comment by lakeinchina** [comment]
额，可以，但是麻烦一点，不是一句话说得清的了，要修改RESHardVideoCore,在updateCameraIndex的时候去更新mediaCodecTextureVerticesBuffer

**Comment by huangsai** [comment]
我这样修改的 还是不可以，你能帮忙 把修改后的代码 贴出来 我看一下吗？

   if (currCamera == Camera.CameraInfo.CAMERA_FACING_FRONT) {
                    directionFlag = resCoreParameters.frontCameraDirectionMode;
                    GLHelper.MediaCodecTextureVertices = new float[]{
                            1.0f, 1.0f,
                            1.0f, 0.0f,
                            0.0f, 0.0f,
                            0.0f, 1.0f};
                } else {
                    directionFlag = resCoreParameters.backCameraDirectionMode;
                    GLHelper.MediaCodecTextureVertices = new float[]{
                            0.0f, 1.0f,
                            0.0f, 0.0f,
                            1.0f, 0.0f,
                            1.0f, 1.0f};
                }

**Comment by lakeinchina** [comment]
你这样改没生效
后面加一句
mediaCodecTextureVerticesBuffer = GLHelper.getMediaCodecTextureVerticesBuffer();
