### ISSUE TITLE
推流异常

### ISSUE THREAD

**Issue by JakeRed** [lakeinchina/librestreaming#118]
软编码下demo推流一段时间后弹出：
                if (resClient.getSendBufferFreePercent() <= 0.05) {
                    Toast.makeText(BaseStreamingActivity.this, "sendbuffer is full,netspeed is low!", Toast.LENGTH_SHORT).show();
                }
我连的是公司的WiFi，推流10分钟后就会这样，再过一段时间demo会重新连接，然后知道连上，可这个是接受不了的，我换了WiFi也有同样的问题，如过可以我想问一下这个问题应该怎么修改呢？

**Comment by lakeinchina** [comment]
我怀疑你们公司网络出口10分钟卡一会..

**Comment by JakeRed** [comment]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 6159 (RenderThread)联想手机报这个，您能给个建议吗？

**Comment by lakeinchina** [comment]
x86手机？可以用hard模式试试
