### ISSUE TITLE
推流的时候，设置视频的窗口为640*360，窗口会压扁拉长，这个是什么原因？

### ISSUE THREAD

**Issue by zhangymloovee** [lakeinchina/librestreaming#12]

**Comment by zhangymloovee** [comment]
而且卡顿现象，比较严重，无论软编码和硬编码。这个有什么什么好的方式来优化？

**Comment by lakeinchina** [comment]
没听明白，设置textuerview的大小为640*360，textureview的layout会被压扁？
prepare的时候设置的大小不一定会是那个大小，会选一个设备支持的，可以在prepare之后用getVideoSize获取。
卡顿不知道指的是什么，录制还是播放。我测试的不是太差的手机都还可以

**Comment by zhangymloovee** [comment]
resConfig.setTargetVideoSize(new Size(720, 480)); 这个改为640*360 ，推流和播放都会拉长。
卡顿是推流的时候，在别的手机上播放，经常会卡顿。

**Comment by lakeinchina** [comment]
拉长普遍做法就是修改view的onmeasure调整比例为视频的比例，类似这样https://github.com/google/grafika/blob/master/src/com/android/grafika/AspectFrameLayout.java
卡顿我测到的基本都是网络问题，而且请更新到最新版本v0.2，之前有个版本有问题

**Comment by zhangymloovee** [comment]
我们现在看到录制出来的，整个画面被拉长了，无论是在android还是ios上看，都是拉长的，有点变形。

**Comment by lakeinchina** [comment]
因为你把一个和屏幕比例不一样的视频拉伸到了屏幕一样大，所以变形了

**Comment by zhangymloovee** [comment]
而且在录制的过程中，自己看自己的时候，经常会卡顿。

**Comment by lakeinchina** [comment]
《自己看自己》是什么意思

**Comment by zhangymloovee** [comment]
直播界面，不是能看到自己么？

**Comment by lakeinchina** [comment]
那叫预览。。后置摄像头能看到自己么
什么手机？什么系统？软硬模式？有没有用滤镜？

**Comment by zhangymloovee** [comment]
其他sdk好像可以设置640_360，我看映客也是 640_368.

**Comment by zhangymloovee** [comment]
预览的界面会有卡顿。
我用的是三星note2，4.3的系统，软编码，没有使用滤镜。

**Comment by lakeinchina** [comment]
可能是性能问题,你可以试试用硬模式是不是也卡吨
640360一般android摄像头都不支持录这个分辨率,也许映客是给缩放了,或者是ios录的

**Comment by zhangymloovee** [comment]
映客是我自己用note2 抓包的。
硬模式也卡顿。

**Comment by lakeinchina** [comment]
迎客是你用note2录制出来的640360视频？
预览都卡顿我也不知道是怎么导致的，预览只是拿图像然后画一下，我也从来没遇到过预览卡顿的情况，

**Comment by zhangymloovee** [comment]
我们这边试了是会卡顿，预览的时候。

**Comment by zhangymloovee** [comment]
用华为的手机、小米的手机，试了都会。

**Comment by zhangymloovee** [comment]
我试了一下，预览卡住的时候，播放在相同的位置也卡。是不是预览线程和编码网络线程，有时会阻塞？

**Comment by lakeinchina** [comment]
soft模式下,你看看queueVideo,accept和queueVideo,abandon的LOG在卡的时候是不是还在周期打,如果不打了说明摄像头就没数据出来
