### ISSUE TITLE
结束推流, 释放资源, 推流服务器是超时中断, 而不是主动中断的

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#120]
如题, 在结束推流是否需要底层通知推流服务器, 要如何操作;

即 释放资源, 结束推流是, 能够调用librtmp的unpublish指令

**Comment by lakeinchina** [comment]
结束推流是会调RTMP_Close额

**Comment by hike2008** [comment]
我看确实最后, 在librtmp源码中会触发 unpublish指令, 可推流服务器并未收到此消息,  不知道是不是触发的判断条件有什么影响
