### ISSUE TITLE
请问这个有没有IOS版本的

### ISSUE THREAD

**Issue by decide15** [lakeinchina/librestreaming#121]
如题，拜谢

**Comment by lakeinchina** [comment]
因为我不怎么会ios，所以没有ios版了，ios的推流一般都基于[VideoCore](https://github.com/jgh-/VideoCore)做
你也可以试试[CPStreamingMedia](https://github.com/ChenPengOnGitHub/CPStreamingMedia)

**Comment by decide15** [comment]
THX!
