### ISSUE TITLE
How to mix Hardfilter

### ISSUE THREAD

**Issue by theblue1102** [lakeinchina/librestreaming#122]
I want mix two hardfilter IconHardFilter and WhiteningHardVideoFilter , can u help me ? thanks so much!

**Comment by lakeinchina** [comment]
use the HardVideoGroupFilter to combine several filter
filters = new LinkedList<>();
        filters.add(new SobelEdgeDetectionHardVideoFilter());
        filters.add(new FishEyeFilterHard());
        filterItems.add(new FilterItem("GroupFilter", new HardVideoGroupFilter(filters)));

**Comment by theblue1102** [comment]
@lakeinchina  thanks so much :D  👍
