### ISSUE TITLE
你好，关于GPU磨皮滤镜失效问题

### ISSUE THREAD

**Issue by decide15** [lakeinchina/librestreaming#124]
你好，在demo中，使用磨皮滤镜(SkinBklurHardVideoFilter),必须先使用一下SeaScapeFilter才能生效，是什么原因，谢谢！

**Comment by lakeinchina** [comment]
我复现不出来。。但是你可以把SkinBklurHardVideoFilter 的shader里面几个mediump改称highp试一下
另外确认一下yStepLoc和xStepLoc不是-1，(stepScale / SIZE_WIDTH)不是0
