### ISSUE TITLE
Idea : Real Time Face Filter - Mask

### ISSUE THREAD

**Issue by developeralp** [lakeinchina/librestreaming#126]
Hello,

![unnamed](https://cloud.githubusercontent.com/assets/22075871/21544809/5db3ef2e-cde3-11e6-91ee-b6f8ad267391.jpg)

How can i develop face filter , mask or effect ?  Like Snapchat and Instagram

I thought this can be implement with Android's FaceDetection 

But i can't get it work , any ideas ?

**Comment by lakeinchina** [comment]
Android's FaceDetector can\`t detect eye&mouth position , it only detect face rectangle.so it think it\`s useless.
you have to use other face detection sdk to find face then use filter put some image on it.
