### ISSUE TITLE
关于sample2d的问题

### ISSUE THREAD

**Issue by chenqian-dev** [lakeinchina/librestreaming#127]
请教下，采集的时候用了两层的offscreen texture，多了次makecurrent（这个操作貌似很耗时），感觉直接用相同的filter去给screen和codec渲染，应该也可以吧？有什么原因吗？（有人说用oes texture没法做滤镜，证实是可以的啊，所以应该不是这个问题吧），请指教下，谢谢（另非常感谢这个库，之前对这方面不太懂，救了我的急）

**Comment by lakeinchina** [comment]
说起来就有点麻烦了，都是有原因的，总的来说是这样：
SamplerOES -裁剪旋转-> Sampler2DA -filter-> Sampler2DB -->screen or codec.

之所以先把SamplerOES转成sampler2d一方面是为了裁剪旋转这样后面就不用再处理细节，另一方面是为了让滤镜可以组合，否则第一个滤镜需要接受SamplerOES第二个需要接受Sampler2d。当然也许可以全程用SamplerOES，但是我没有找到办法创建SamplerOES的纹理。另外网上基本都是Sampler2d的shader，也方便移植一点点。

还有之所以不让滤镜直接绘制给screen或者codec，是因为对复杂的滤镜来说绘制是很耗时的。直接绘制给screen或者codec需要绘制两遍。而原样复制一遍是很快的（应该不会比这个更快了），所以我用了一次滤镜绘制加两次快速复制而不是两次滤镜绘制。

我其实也不想用offscreen的，但是由于推流和预览是完全分离的（之前的版本预览推流不分开的所以没有这个），用户完全可以不预览直接推流也可以只预览不推流，甚至可以在activity中预览推流的时候关闭activity关闭预览然后再开一个悬浮窗继续预览并且保持推流不断。但是camera的textrue是必须绑定上下文的要不然不能updateTexImage。所以这时候就不知道绑给谁了，谁都不可靠可能不存在，所以加了一个offscreen。所以就是现在有3个上下文的情况。不过我没觉得makecurrent很慢，速度上我只觉得filter复杂的时候才慢，比如那个seascape。

**Comment by chenqian-dev** [comment]
我想也是为了第三方的shader。。。不过还是感觉多了一层复制，心里不太舒服~，还有旋转剪裁不适用投影？有什么原因吗？我觉得投影似乎更简单。。

**Comment by lakeinchina** [comment]
假如滤镜要花30毫秒，复制只要3毫秒，那绘制屏幕和编码器需要60毫秒，而现在只需要36毫秒。这是不直接绘制给屏幕和编码器的主要原因。
转换成sampler2D那一步的主要原因是groupfilter，如果现在要两个滤镜组合，那第一个滤镜shader里面要写samplerExternalOES第二个要写sampler2D，那现在要单独使用第二个滤镜呢或者交换两个滤镜的顺序呢，每个滤镜还要写两个shader。。分别对应samplerExternalOES和sampler2D
