### ISSUE TITLE
某机型推流失败的问题

### ISSUE THREAD

**Issue by decide15** [lakeinchina/librestreaming#128]
#87 和这个问题是同一个，硬编码出现。
logcat有报错信息：
E/OMXNodeInstance: getParameter(1:google.aac.encoder, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
最新版的demo
Flyme 5.1.11.1A
Android 5.1
魅蓝m3 note
硬编码，软编正常

**Comment by lakeinchina** [comment]
软编正常？哪应该不是这个log，你可以打断点看一下在哪挂的

**Comment by decide15** [comment]
没有挂。我跟了一下。在VideoSenderThread里面，最终获取的sendRealData的数据量很少，Type是Video的数据量非常小，只有90个字节（一帧？），因为没有写过关于媒体流方面的项目，很多知识不懂，编码那块也不了解，跟不进去。。我同时又去看了Yasea项目，同一款机型也有同样的问题。
