### ISSUE TITLE
直播推流端画面时常会卡顿

### ISSUE THREAD

**Issue by snube** [lakeinchina/librestreaming#13]
推流过了一会或者时间久点，有时候会间歇性出现推流端预览画面都卡顿的情况，这个卡顿延续时间不长

**Comment by lakeinchina** [comment]
某个手机出现？我从来没遇到过预览也会卡顿的情况

**Comment by snube** [comment]
魅蓝2，小米的手机也会

**Comment by lakeinchina** [comment]
我有的手机测到过，但是都是由于系统回调帧就是慢了，帧间隔经常跳掉100毫秒左右，所以就卡顿了一下。
你可以在setOnFrameAvailableListener。onavailable打个log，看看是不是回调间隔时间变长了
