### ISSUE TITLE
MediaCodec解码surface问题

### ISSUE THREAD

**Issue by chenqian-dev** [lakeinchina/librestreaming#130]
请教下，我要用MediaCodec解码到offScreen的纹理，然后再处理这个纹理，之后显示到屏幕上，这样可行吗？
MediaCodec解码接收的纹理有什么要求吗？也是2d的就行吗？

是不是只需要给MediaCodec一个绑定fbo的2d的纹理，然后解码后可以直接用这个2d的纹理，不需要再想oes那样再一层fbo就能使用？

**Comment by notedit** [comment]
是2d的    fbo 绑定一个普通的2d纹理就好

**Comment by lakeinchina** [comment]
我没用过mediacodec直接解码给surface，但是应该可以直接用，估计是2d的，我之前调研的时候都没办法创建出oes的纹理

**Comment by chenqian-dev** [comment]
。。我用oes的格式去读取MediaCodec解码后的surfacetexture可以正确读到，如果用2d的直接bindTextureImage: error binding external image:   @@0x502。。。。。你确定可以用2d的显示在屏幕上？。。@notedit

**Comment by chenqian-dev** [comment]
现在MediaCodec和渲染全程都用oes 就可以正确解码并且渲染

**Comment by lakeinchina** [comment]
那看来凡是和系统相关的都是oes格式，你创建oes格式的纹理是用gl的api创建的么？ @chenqian2651489

**Comment by notedit** [comment]
为什么不可以

**Comment by notedit** [comment]
MagicCamera 这个项目里的代码可以参考

**Comment by chenqian-dev** [comment]
它都没有用到MediaCodec吧。。。

**Comment by chenqian-dev** [comment]
我是创建了一个ScreenEGLWrapper之后直接genTexture，然后用这个直接new一个SurfaceTexture给mediacodec。。

**Comment by chenqian-dev** [comment]
希望你来个系统的专业点的。。我对opengles不是太了解

**Comment by lakeinchina** [comment]
GLES20.glGenTextures(1, frameBufferTex, 0);
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, frameBufferTex[0]);
        GLES20.glTexImage2D(GLES20.GL_TEXTURE_2D, 0, GLES20.GL_RGBA, width, height, 0, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, null);
就是这样直接把GL_TEXTURE_2D换成oes吗？我之前试的时候会产生glerror

**Comment by notedit** [comment]
我也没用  MediaCodec    我是拿到yuv数据生成一个2d texutre  然后渲染

**Comment by notedit** [comment]
@lakeinchina  不能这么转    oes 是为外设专门设计的  基本上是为摄像头设计的   读写速度都比较差

**Comment by chenqian-dev** [comment]
所以MediaCodec解码出来的还是一个yuv的纹理。。。

**Comment by notedit** [comment]
api 23  或者  24  引入了一个新的api   mediacodec 可以直接解码到一个surface上   

现在还太新  用不了

**Comment by chenqian-dev** [comment]
能不能搞个群或者别的啥。。这也太麻烦了交流？

**Comment by SR1s** [comment]
关于纹理的处理建议看下 http://github.com/google/grafika 这个项目
