### ISSUE TITLE
不能debug

### ISSUE THREAD

**Issue by yaooort** [lakeinchina/librestreaming#131]
你好，不能打断点，需要怎么配置，网上没找到合适的答案，如果知道请告知，目前只要debug就会报

Now Launching Native Debug Session
Attention! No symbol directories found - please check your native debug configuration
Execution finished because of: E0112 14:47:13.489866 4055671744 ProtobufClient.cpp:142] ERROR, no such host as localhost

**Comment by lakeinchina** [comment]
要debug至少把NDK_DEBUG=1打开，这个和工程没什么关系，都是ndk开发的相关知识，ndk打断点调试有点麻烦，这个工程ndk代码不多，我都是直接打log的
