### ISSUE TITLE
How do we update Y position  for IconFilterSoft ?

### ISSUE THREAD

**Issue by pensokha** [lakeinchina/librestreaming#133]
I have try following but does not work.

private  int yPos=0;

    public void setYPos(int y) {
        yPos = y;

    }

    @Override
    public boolean onFrame(byte[] orignBuff, byte[] targetBuff, long presentationTimeMs, int sequenceNum) {
        System.arraycopy(orignBuff, 0, targetBuff, 0, SIZE_TOTAL);
        for (int y = 0; y < iconH; y++) {
            for (int x = 0; x < iconW; x++) {
                if (imageByte[y * iconW + x] != 0) {
                    targetBuff[xPos + (y + yPos) * SIZE_WIDTH + x] = imageByte[y * iconW + x];
                    if ((x + xPos) % 2 == 0) {
                        if (x % 2 == 0) {
                            targetBuff[SIZE_Y + (y / 2 + yPos) * SIZE_WIDTH + x + xPos] = imageByte[iconYSize + (y / 2) * iconW + x];
                            targetBuff[SIZE_Y + (y / 2 + yPos) * SIZE_WIDTH + x + xPos + 1] = imageByte[iconYSize + (y / 2) * iconW + x + 1];
                        } else {
                            targetBuff[SIZE_Y + (y / 2 + yPos) * SIZE_WIDTH + x + xPos] = imageByte[iconYSize + (y / 2) * iconW + x+1];
                            targetBuff[SIZE_Y + (y / 2 + yPos) * SIZE_WIDTH + x + xPos + 1] = imageByte[iconYSize + (y / 2) * iconW + x];
                        }
                    }
                }
            }
        }
        return true;
    }

please advise.

**Comment by lakeinchina** [comment]
targetBuff[xPos + (y + yPos) * SIZE_WIDTH + x]
should be
targetBuff[xPos + (y + 2*yPos) * SIZE_WIDTH + x]

but I suggest you use hard mode

**Comment by pensokha** [comment]
tried but does not work correct

**Comment by pensokha** [comment]
I have try hard mode is working perfect
