### ISSUE TITLE
RTMP 

### ISSUE THREAD

**Issue by surabhi1694** [lakeinchina/librestreaming#137]
hey i'm getting error code 9 all the time i successfully connected with my server 
but as i start streaming it show's me error code can you please tell me what is problem and solution?
thanks.....

**Comment by notedit** [comment]
error code 9  may be the server error,  can not connect to server.

check your server.

**Comment by lakeinchina** [comment]
onOpenConnectionResult return 0?
and  onWriteError return 9  immediately?

**Comment by surabhi1694** [comment]
i'm able to connect to my server it returns me my host ip as well but as i start to recording video it gives me error code 9 yes i get result 0 and it print my server id but after that it gives onWriteError return 9.

**Comment by surabhi1694** [comment]
at server in error blog i get  *33 access forbidden by rule, client: 192.168.*.*, server: 0.0.0.0:1935
2017/03/01 18:53:25 [alert] 26970#0: unknown process 27059 exited on signal 9
i don't understand how to solve it 
here is my config file : i want to stream video from android and display on other phone with rtmp live url
i'm using nginx rtmp server please guide me if there is something with config file

#user  nginx;
worker_processes  auto;

error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

       location ~ /\.  {
            root /usr/local/nginx;
            index  index.html;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        # root html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
           deny  all;
        }
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
rtmp {
    server {
            listen 1935;
           chunk_size 8192;

   application live {
                     # enable live streaming
                    live on;
                    interleave on;
                    record all;
                    record_path  /usr/local/nginx/rtmp;
                    allow play all;
                    allow publish 127.0.0.1;
                    allow publish 192.168.*.***;
                    deny publish all;
            # On every pusblished stream run this command (ffmpeg)
            # with substitutions: $app/${app}, $name/${name} for application & stream name.
            #
            # This ffmpeg call receives stream from this application &
            # reduces the resolution down to 32x32. The stream is the published to
            # 'live360p' application (see below) under the same name.
            #
            # ffmpeg can do anything with the stream like video/audio
            # transcoding, resizing, altering container/codec params etc
            #
            # Multiple exec lines can be specified.

          #exec_push ffmpeg -re -i /usr/local/nginx/SampleVideo.mp4 -vcodec flv -acodec copy -s 32x32
                        #-f flv rtmp://localhost:1935/live/myStream;

                   exec ffmpeg -re -i rtmp://192.168.*.***:1935/live/$name
                         -c:v libx264 -c:a libfaac -ar 44100 -ac 1
                               -f flv rtmp://192.168.1.212:1935/live360p/${name} ;

}
   application live360p {
                    live on;
                    interleave on;
                    #record all;
                    #record_path  /usr/local/nginx/rtmp;
                    push rtmp://192.168.*.***:1935/live/$name;
        }
    }
}

**Comment by lakeinchina** [comment]
I'm not familiar with rtmp server config, cannot provide help.

**Comment by surabhi1694** [comment]
oh... ok

**Comment by surabhi1694** [comment]
hey do i need to implement android-ndk for this code?
please guide me

**Comment by lakeinchina** [comment]
can`t understand...
jni directory contains the native code.It should work well.

**Comment by surabhi1694** [comment]
actually i did'nt install android-ndk in my project nor cmake for native libs . so do i have to install android ndk for this project? or it will run properly with this jnilibs folder!

**Comment by surabhi1694** [comment]
what i meant is i just want to stream my live video to server so do i need to have ndk for your project?

**Comment by lakeinchina** [comment]
".so" is already builded in libs dir.
you don`t have to build native code.
