### ISSUE TITLE
请教个IconHardFilter滤镜中图片旋转缩放问题

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#138]
你好，请问下如果想对IconHardFilter滤镜中加的图片进行旋转缩放处理该咋弄呢？
我试过准备bitmap的时候先旋转好，但是此时的rectf坐标比较难弄，如何在gl里面对这个滤镜的image texture进行旋转呢？（尝试了下对顶点position进行Matrix处理，发现连相机画面也一起旋转了💔）。

**Comment by lakeinchina** [comment]
那个位置我是在片段着色器里算的，大概算是最丑的方式，硬改成可以旋转的也是可以的，也比较方便，就是计算麻烦一点，我建议就用这个方式。
先绘制视频再绘制icon可能比较优雅，也很容易控制旋转缩放，就是透明度问题可能要启用3d才能解决了。
也可以做一个和视频一样大的bitmap，所有东西都用安卓API往这里面画，然后一次性画到视频里面。

**Comment by jtyang** [comment]
嗯嗯，多谢！先在着色器里计算下试试，不行的话就用安卓api处理好的bitmap算了。
