### ISSUE TITLE
nexus 5x后置摄像头视频旋转了180度

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#14]
nexus 5x后置摄像头视频旋转了180度

**Comment by lakeinchina** [comment]
nexus摄像头怎么都这么奇葩。。  Camera.getCameraInfo(Camera.CameraInfo.CAMERA_FACING_FRONT, cameraInfo);读一下旋转参数调一下就好了
话说你测试机挺全啊

**Comment by jtyang** [comment]
嗯嗯，我会尽量把我用这个库遇到的问题在这说下！

**Comment by lakeinchina** [comment]
我已经更新了sample，但是侧不了，你可以试试
