### ISSUE TITLE
显示卡顿

### ISSUE THREAD

**Issue by xulingchung2016** [lakeinchina/librestreaming#141]
楼主，显示视频会卡顿，是不是和TextureView有关啊，能换成surfaceView么？

**Comment by lakeinchina** [comment]
只有预览卡顿推流不卡顿？没碰到过。应该和TextureView没啥关系，你要是想换成surfaceView很容易，把
```java
public static void initScreenGL(ScreenGLWapper wapper, EGLContext sharedContext, SurfaceTexture screenSurface) 
```
SurfaceTexture改成surfaceView的Surface就行了，上层的都改掉

**Comment by xulingchung2016** [comment]
好像和我当时手机内存有关系，清除内存以后就好了。楼主，还想请教个问题，如果要保存录制的视频到本地在哪里处理。可以不推送。就是多一种模式。
