### ISSUE TITLE
Compiling x86 , x64

### ISSUE THREAD

**Issue by PreDeToR** [lakeinchina/librestreaming#142]
Hi Guys

Looking at this issue: 
https://github.com/lakeinchina/librestreaming/issues/80

Once I have this module/system checked out,made the changes from the link.
How do I force it to compile the new library files?

Regards
Danie

**Comment by lakeinchina** [comment]
Install android NDK dev environment then use the ndk-build command

**Comment by developeralp** [comment]
Hello @PreDeToR,

You should edit Application.mk like this,

APP_ABI := armeabi-v7a arm64-v8a x86 armeabi 

Also you should add your ndk's location to path (if you're on windows)

And you can get .so files by running ndk-build on Application.mk file's dir (from cmd , on your jni library)

**Comment by udongeex** [comment]
@developeralp @lakeinchina 
Hello, I did try to add APP_ABI := armeabi-v7a arm64-v8a inside Application.mk but when I run ndk-build, I ran into the below error:
![image](https://user-images.githubusercontent.com/29280577/79672520-10fdd100-81fd-11ea-8597-50cf3ce98158.png)
Please help me with it, I'm trying to generate arm64-v8a folder to upload on GooglePlay
