### ISSUE TITLE
录像保存本地

### ISSUE THREAD

**Issue by xulingchung2016** [lakeinchina/librestreaming#143]
楼主，能加个录像保存到本地的接口吗？看了半天不知道在哪里处理。麻烦了

**Comment by lakeinchina** [comment]
参考这个 #68

**Comment by xulingchung2016** [comment]
大神，我安装那样做一后，混合器无法stop 报异常。 Can't stop due to wrong state.

**Comment by xulingchung2016** [comment]
能包我看一下吗？感谢啊

**Comment by lakeinchina** [comment]
这啥也看不出来
注意要addTrack()完之后才能star()t，才能writeSampleData()，结束的时候signalEndOfInputStream()，取到（einfo.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM）的时候再stop()和release()

**Comment by xulingchung2016** [comment]
我找到原因了，谢谢了，大神！再问一下，这个支持只做音频直播吗？是不是就audioClient.start()就可以了。

**Comment by lakeinchina** [comment]
吧videoclient.start和stop注释掉应该就行

**Comment by jtyang** [comment]
@xulingchung2016 请问下录制这个你是怎么加的，我加了之后，得到的mp4声音正常，但视频却只有一帧。

**Comment by yuchf** [comment]
@xulingchung2016 请问下具体怎么实现的，谢谢

**Comment by haijiaoqiufeng** [comment]
@xulingchung2016 请问下具体怎么实现的?怎么处理的音频和视频?
