### ISSUE TITLE
声音噪音太大

### ISSUE THREAD

**Issue by xulingchung2016** [lakeinchina/librestreaming#144]
大神，声音去噪处理有没有做啊。噪音有点大

**Comment by lakeinchina** [comment]
没有

**Comment by xulingchung2016** [comment]
大神，有什么方法可以处理一下吗？现在声音听不清楚，很卡，不流畅是怎么回事？

**Comment by lakeinchina** [comment]
不清楚。没遇见过

**Comment by darkSuperman** [comment]
我也是，噪声很大，音频用的是AAC编码的吗？

**Comment by darkSuperman** [comment]
大神，你估计噪声和什么因素有关？有解决方案吗？

**Comment by darkSuperman** [comment]
我改怎么样吧PCM的音频编码格式换为AAC，一换就报非法参数异常错误

**Comment by lakeinchina** [comment]
不清楚噪声很大是多大...我没发现过这种情况,这个问题和编码没关系,只和话筒有关系

**Comment by darkSuperman** [comment]
谢谢你的回复，我前段时间解决了这个问题。
if (audioFilter instanceof SetVolumeAudioFilter) {
       SetVolumeAudioFilter blackWhiteFilter = (SetVolumeAudioFilter) audioFilter;
        blackWhiteFilter.setVolumeScale((float) (progress / 100.0));//原先是10.0，我改成100.0扩大后就没噪音了，那个噪音感觉是收集音源范围太广了,推流声音设小点没问题，调大了很多噪音。
                    }
