### ISSUE TITLE
请教一个textHardFilter的问题

### ISSUE THREAD

**Issue by xulingchung2016** [lakeinchina/librestreaming#147]
大神，由于本人能力有限，看了好久都没有看懂怎么把textHardfilter添加到实时视频里的。能说一下流程原理吗？有个简单的小demo可以供学习最好了。麻烦了！！！！

**Comment by lakeinchina** [comment]
text原理就是用安卓的api绘制文字到bitmap上，然后把bitmap画到视频里面

**Comment by xulingchung2016** [comment]
那这样会不会很耗时啊？是画到视频的每一帧里吗？这个有什么推荐的文章可以学习一下吗？

**Comment by lakeinchina** [comment]
OpenGL本来就是这么用的，它本身也不包含任何绘制文字的功能...你可以参考OpenGL ES 2.0 Programming Guide

**Comment by xulingchung2016** [comment]
OpenGl不是不能画文本吗？

**Comment by xulingchung2016** [comment]
大神，有没有了解过FFmpeg 为实时视频添加文本怎么做的？

**Comment by lakeinchina** [comment]
别的封装库会提供绘制文本的功能，gl本身没有
ffmpeg我不太了解，但是一般用avfilter加水印

**Comment by xulingchung2016** [comment]
哦，那您这个项目是怎么把bitmap画到视频里的呢？哪个类里做了这个功能？

**Comment by lakeinchina** [comment]
textHardfilter做了这个功能

**Comment by xulingchung2016** [comment]
大神，感谢啊！终于有点眉目了，那软编码的为什么不能绘制呢？是不是没有surfaceTure啊？

**Comment by lakeinchina** [comment]
软编码当然可以绘制，只是我懒的写。。

**Comment by xulingchung2016** [comment]
那这些视频特效都是通过opengl 来做到的吧？关键不太熟悉opengl api,你在onDraw里写的那些都看不懂。
