### ISSUE TITLE
How I can stream video from uvc usb camera? 

### ISSUE THREAD

**Issue by bently93** [lakeinchina/librestreaming#149]
I get a frame byte buffer from uvc usb camera in pixel format PIXEL_FORMAT_RGB565. How i can stream video?

**Comment by lakeinchina** [comment]
It doesn`t support it.you have to modify the code to achieve that.
Basically,you have to write you own ResVideoClient.

**Comment by MattWanjia** [comment]
> It doesn`t support it.you have to modify the code to achieve that. Basically,you have to write you own ResVideoClient.

Hi. Any support for a UVC Camera as at now?
