### ISSUE TITLE
美白效果

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#15]
你好，美白效果如何能优化一下。或者人脸识别美白。目前效果仅仅全白高亮。

**Comment by zhangymloovee** [comment]
你们会卡顿么？推流的时候。

**Comment by lakeinchina** [comment]
我是不会做人脸标点的，所以最多就是识别一下肤色。
美白其实就是一个颜色对应表，把黄色什么的对应成白色。但是这个颜色表不是很容易就能调好的

**Comment by androidwzq** [comment]
推流还好，和网络环境有很大关系。另外码率1M，帧率25-30 都是差不多的

**Comment by zhangymloovee** [comment]
我看映客的，只需要480的码率，帧率在18.

**Comment by androidwzq** [comment]
斗鱼的横屏 可以设置码率帧率，横屏是固定的参数。
你有微信么？加下被 或者你在公告发个微信群 或者qq交流群啥的

**Comment by lakeinchina** [comment]
可以把qq发我邮箱
