### ISSUE TITLE
请问个录屏问题

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#151]
使用MediaMuxer将视频保存为mp4，在VideoSenderThread和AudioSenderThread分别加上addTrack和writeSampleData后，保存的mp4文件声音正常，但视频只显示一帧；但是如果AudioSenderThread不加MediaMuxer代码，即只录制视频，这样保存的mp4视频播放却又是正常的，不知道是否有遇到类似情况？thanks！

**Comment by lakeinchina** [comment]
我之前试过没什么问题,就是用Mediauxer有个坑,音视频都addrack之后才能start,然后再wirtesampledata

**Comment by jtyang** [comment]
是否方便提供下你的demo呢？

**Comment by lakeinchina** [comment]
demo没有了,给别人改的.你是不是时间戳的问题,要从0开始

**Comment by jtyang** [comment]
时间戳？是指VideoSenderThread和AudioSenderThread中的startTime吗（其他地方貌似没看到跟时间戳相关的）？这两个startTime和这个librestreaming库中的计算方式是一样的。不过感觉这两个时间貌似跟混合保存到本地没啥关系。还是说第一帧BufferInfo的presentationTimeUs字段要手动指定为0？

**Comment by lakeinchina** [comment]
就是writesampledata的时候需要同样把时间戳减去初始时间,就是把时间戳从0开始
