### ISSUE TITLE
软件编码时，绘制960*540 颜色值不对

### ISSUE THREAD

**Issue by sevenmine** [lakeinchina/librestreaming#154]
绘制960*540 时画面色值不对，看上去像是 U、V没有搞对

**Comment by lakeinchina** [comment]
有图吗?怎么个不对法

**Comment by sevenmine** [comment]
找到原因了，是opegl默认按4字节对齐的， 当540*960分辨率下，绘制U、V时，width = 540/2  ,270不是4的倍数，因此需要制定下opengl 按 2字节对齐就好了  GLES20.glPixelStorei(GLES20.GL_UNPACK_ALIGNMENT, 2);

**Comment by lakeinchina** [comment]
感谢分享
