### ISSUE TITLE
是否有类似PBO这类代替glReadPixels的方案

### ISSUE THREAD

**Issue by sevenmine** [lakeinchina/librestreaming#156]
楼主你好，目前我集成了这个项目中的滤镜模块，发现采用的是FBO的方式，这种方式下的glReadPixels 在armv7下表现还可以，720P加上磨皮和滤镜也差不多40、50ms。 但到了arm64架构下却发现glReadPixels 这个函数及其不稳定，在30~100ms之间跳动。 我查了好多资料，都说是arm64下对glReadPixels的指令优化不够好。 网上很多又说可以用PBO在解决glReadPixels慢的问题。 但我对openGL不是很了解，看到你GLESTest这个项目中用到了PBO，所以想请楼主指教下在这个项目中如何使用PBO来代替glReadPixels。 谢谢

**Comment by lakeinchina** [comment]
我试过pbo,感觉也不是很好,表现也不稳定,一直都没有找到一个满意的办法来读取gl里的图像.
[GLRenderThread3](https://github.com/lakeinchina/GLESTest/blob/master/app/src/main/java/me/lake/gleslab/test3/GLRenderThread3.java)
建一个就行了,建两个是我瞎试的

**Comment by sevenmine** [comment]
好的，我再研究下，谢谢了。 就是感觉android的openGL太蛋疼了，开了API，又不好用。 不像iOS，gpu和cpu是共享内存的，数据拷贝就方便多了

**Comment by sevenmine** [comment]
楼主，有qq或是其他的联系方式么， 我在原来glReadPixels 那里，修改为PBO方式读取， 但glMapBufferRange 一直返回的是null， 不知道什么原因，想请教下

**Comment by sevenmine** [comment]
`   private void drawFrameBuffer() {
        GLHelper.makeCurrent(offScreenGLWapper);
        boolean isFilterLocked = lockVideoFilter();
        if (isFilterLocked) {
            if (videoFilter != innerVideoFilter) {
                if (innerVideoFilter != null) {
                    innerVideoFilter.onDestroy();
                }
                innerVideoFilter = videoFilter;
                if (innerVideoFilter != null) {
                    innerVideoFilter.onInit(mCameraWidth, mCameraHeight);
                }
            }
            if (innerVideoFilter != null) {
                synchronized (syncCameraTextureVerticesBuffer) {
                    innerVideoFilter.onDirectionUpdate(directionFlag);
                    innerVideoFilter.onDraw(sample2DFrameBufferTexture, frameBuffer, shapeVerticesBuffer, cameraTextureVerticesBuffer);
                }
            } else {
                drawOriginFrameBuffer();
            }
            unlockVideoFilter();
        } else {
            drawOriginFrameBuffer();
        }
        long start = System.currentTimeMillis();

        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, frameBuffer);
        drawPBO();
//        if(pixBuffer == null){
//            pixBuffer = ByteBuffer.allocate(mCameraWidth * mCameraHeight * 4);
//        }
//        GLES30.glReadPixels(0, 0, mCameraWidth, mCameraHeight, GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, pixBuffer);
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, 0);
        long end = System.currentTimeMillis();
        Log.e("aa","glReadPixels: " + (end - start));
    }`

`    private void initPBO(){
        IntBuffer i = IntBuffer.allocate(1);
        GLES30.glGenBuffers(1, i);
        mPBO = i.array()[0];
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, mPBO);
        GLES30.glBufferData(GLES30.GL_PIXEL_PACK_BUFFER, 4 * mCameraWidth * mCameraHeight, null, GLES30.GL_DYNAMIC_READ);
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, 0);
    }

    byte[] pixelArray;
    private void drawPBO(){
        long start = System.currentTimeMillis();
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, 0);
        GLES30.glReadBuffer(GLES30.GL_BACK);
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, mPBO);
        if(pixelArray == null){
            pixelArray = new byte[mCameraWidth * mCameraHeight * 4];
        }
        HomeActivity.readPixel(pixelArray, GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, 0);
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, mPBO);
        Buffer buf = GLES30.glMapBufferRange(GLES30.GL_PIXEL_PACK_BUFFER, 0, mCameraWidth * mCameraHeight * 4, GLES30.GL_MAP_READ_BIT);
        ByteBuffer b = ((ByteBuffer) buf).order(ByteOrder.nativeOrder());
        b.get(pixelArray, 0, mCameraWidth * mCameraHeight * 4);
        GLES30.glUnmapBuffer(GLES30.GL_PIXEL_PACK_BUFFER);
        GLES30.glBindBuffer(GLES30.GL_PIXEL_PACK_BUFFER, 0);
        long end = System.currentTimeMillis();
        Log.e("aa","PBO readPixel: " + (end - start));
    }`

这是大概的代码

**Comment by lakeinchina** [comment]
你回复了?这里怎么看不到
readPixel函数是个native函数,有注释掉的代码,好像这个glMapBufferRange得在jni里用,具体记不清了
