### ISSUE TITLE
可以将一组图片作为视频源录进去吗？

### ISSUE THREAD

**Issue by zhonglikui** [lakeinchina/librestreaming#157]
想实现从手机上选择一组图片，然后录制到视频里面去，目前有两种想法，一个是作为IconHardFilter设置大小为全屏，还有一个是把图片转化成录制需要的数据，但是该怎样才可以不启用摄像头也能录制呢？对于这个需求，前面的两种想法可行吗？

**Comment by lakeinchina** [comment]
用iconhardfileter就行,但是不启用摄像头的话,必须要改代码才能实现了

**Comment by zhonglikui** [comment]
还要有添加背景音乐的功能，需要改哪里的代码呢？改动大吗？

**Comment by lakeinchina** [comment]
需要写一个audiofilter,把音频和背景音乐混合.
主要难点是需要用其他的东西把mp3解码成pcm

**Comment by zhonglikui** [comment]
靠MediaCodec和MediaMuxer可以将图片合成视频吗？

**Comment by lakeinchina** [comment]
可以，这俩只是编码器和复用器，具体视频内容你填啥都行
