### ISSUE TITLE
为什么硬件模式要创建那么多个surface

### ISSUE THREAD

**Issue by silentsugar** [lakeinchina/librestreaming#158]
不是很明白为什么要创建3个surface，initOffScreenGL，initScreenGL，initMediaCodecGL，可以说下大概的流程和原理吗？

**Comment by lakeinchina** [comment]
#127 
screen是用来绘制到屏幕上的
mediacodec是用来绘制到编码器的，这两个省不了
offscreen是为了提供从camera取图像并进行滤镜处理的，其实也可以直接用screen或者mediacode
之所以不用是为了让“预览+不推流”，“不预览+推流”，“不预览+不推流”三种情况都能使用，所有弄了一个和预览推流无关的offscreenglContext
