### ISSUE TITLE
aarch64    CPU架构的手机运行时崩溃，log如下

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#159]
# GLThread
java.lang.RuntimeException
eglMakeCurrent,failed:EGL_BAD_NATIVE_WINDOW

me.lake.librestreaming.core.GLHelper.makeCurrent(GLHelper.java:259)
me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.uninitScreenGL(RESHardVideoCore.java:648)
me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.handleMessage(RESHardVideoCore.java:373)
android.os.Handler.dispatchMessage(Handler.java:111)
android.os.Looper.loop(Looper.java:210)
android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lakeinchina** [comment]
这个和64位cpu没关系，是gl兼容性的问题

**Comment by hike2008** [comment]
那如何处理这种情况比较好呢
