### ISSUE TITLE
概率主线程堵塞

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#16]
当网络环境不好的时候，退出推流直播视频，有概率主线程堵塞现象。

**Comment by lakeinchina** [comment]
请更新到最新的版本，如果还有问题再反馈下软模式还是硬模式

**Comment by androidwzq** [comment]
就是最新版本的 硬模式。退出来的时候 网络不好 会卡住，以前最开始的时候 是基本都卡，可能是线程锁的原因 我看你应该改了。最新版 也会有概率卡事件，不过仅是网络条件不好的情况下，概率出现

**Comment by lakeinchina** [comment]
如果会卡住，那也应该是不可能和网络差有关系，网络线程和ui线程没关系，网络线程再怎么卡住也不会影响ui线程的

**Comment by jtyang** [comment]
这个有可能是停止的时候线程join的原因，我之前测试发现join有可能会一直阻塞，导致ui卡死，可以join（100）这样试试。
