### ISSUE TITLE
输出视频画质是720P，我应该设置多大的码率比较好。

### ISSUE THREAD

**Issue by darkSuperman** [lakeinchina/librestreaming#161]
resConfig.setTargetVideoSize(new Size(1280, 720)).

resConfig.setBitRate(？？？ * 1024);
还有，硬模式下磨皮滤镜好像没有起到作用resClient.setHardVideoFilter(new SkinBlurHardVideoFilter(3))，还会导致预览画面帧数很低，这是gpu不兼容吗？但是我设置别的滤镜resClient.setHardVideoFilter(new WhiteningHardVideoFilter())是有用的.有劳作者答疑 ^_^

**Comment by lakeinchina** [comment]
1000*1024左右爸，具体可以自己测以下，看你需要要多清晰了
磨皮滤镜没效果是浮点数精度的问题，把shader里面的mediump改成highp
