### ISSUE TITLE
Is it possible to stream with extra audio file?

### ISSUE THREAD

**Issue by ltpquang** [lakeinchina/librestreaming#166]
Hi there,

Is it possible for `RESRtmpSender` to send one video stream and two audio streams at the same time?

Currently `RESRtmpSender` is able to send one video stream (from `RESVideoClient`, using `RESFlvDataCollector`) and one audio stream (from `RESAudioClient`, using `RESFlvDataCollector` too). Now I want to send one more audio stream from an audio file beside the two current ones. Is it possible?

**Comment by lakeinchina** [comment]
It doesn`t support two audio stream
