### ISSUE TITLE
推流的封装格式

### ISSUE THREAD

**Issue by xulingchung2016** [lakeinchina/librestreaming#167]
大神，请问推流的封装格式不是.flv吗？怎么flash player 播放就崩溃

**Comment by lakeinchina** [comment]
不会把，我之前试过flash player没问题

**Comment by xulingchung2016** [comment]
之前我用red是没问题的，现在用nginx 网页上是打不开的。

**Comment by lakeinchina** [comment]
我们的服务器一直都是用的nginx，应该不是推流的问题
