### ISSUE TITLE
EGL14.eglSwapBuffers()返回false

### ISSUE THREAD

**Issue by RunningSnailGOAhead** [lakeinchina/librestreaming#171]
运行时间稍长，EGL14.eglSwapBuffers()就会返回false，主动抛出运行异常。这个问题有什么好的方法可以解决么？

**Comment by lakeinchina** [comment]
这个不清楚，某些别的原因导致的，可以尝试忽略这个错误，看看后面是否正常

**Comment by longhailin** [comment]
发现在华为 Mate P9 下，这个bug必现
