### ISSUE TITLE
hai lake~ 来个可以只推音频的功能怎么样

### ISSUE THREAD

**Issue by WangShuo1143368701** [lakeinchina/librestreaming#178]
市面上有些需要只推音频流，大佬要不要来一发更新，或者给点提示怎么修改~

**Comment by lakeinchina** [comment]
把videoClient.startStreaming(dataCollecter);和videoClient.stopStreaming();注释掉应该就能只推音频，但是其实rtmp的配置并不正确

**Comment by WangShuo1143368701** [comment]
(⊙o⊙) 请问大佬，怎么让只推流不预览啊？ startPreview(SurfaceTexture surfaceTexture, int visualWidth, int visualHeight)。这个采集数据的方法不是必须调？然后必须预览？

**Comment by WangShuo1143368701** [comment]
new 一个surfaceTexture传入吗

**Comment by lakeinchina** [comment]
不调startPreview直接startsteaming就开始推流了

**Comment by WangShuo1143368701** [comment]
看了源码，果然是这样，感谢大佬。凑着机会再问一个。。。我自己写了一个这样的方法 resConfig.setTargetPreviewSize(new Size(cameraPreviewSize.width, cameraPreviewSize.height));
目的是想把预览和video分开。后来发现好像OpenGL根据video的尺寸裁剪后，才把数据复制给预览和video,这样我之前说做的是不起效果的。（裁剪后的尺寸给预览显示，感谢图形变大，距离拉近了） 。怎么修改可以把不裁剪的数据给预览，然后把裁剪后的数据给video推流

**Comment by lakeinchina** [comment]
这个不是几行就可以改好的，有点麻烦，因为设计上本来就是先处理完再把结果给预览或者推流的，因为想保证用户和主播看到的画面是完全一致的

**Comment by WangShuo1143368701** [comment]
thankyou~
