### ISSUE TITLE
rtmp重联机制

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#18]
rtmp 网络中断 重联机制如何添加？在onWriteError回调中 补充？

**Comment by lakeinchina** [comment]
onOpenConnectionResult是连接结果，如果失败可以去重启。
onWriteError的参数是连接成功之后写数据连续失败次数，sample里面是连续100失败别就重启一次。
所以当前sample的效果是如果连接不成功就什么也不干，如果连接成功之后写数据过程中连续失败100次就重启。
不包含判断当前是否联网的代码。
