### ISSUE TITLE
大神，硬模式下怎么把编码之前的数据回调出来，以便接入第三方美颜贴纸功能

### ISSUE THREAD

**Issue by WangShuo1143368701** [lakeinchina/librestreaming#185]

**Comment by WangShuo1143368701** [comment]
还有想请教下，这里面的四个参数都是什么   
innerVideoFilter.onDraw(sample2DFrameBufferTexture, frameBuffer, shapeVerticesBuffer, cameraTextureVerticesBuffer);   感激不尽！

**Comment by lakeinchina** [comment]
这个不会opengl是看不懂的，如果第三方美颜支持opengl处理，就能接入
