### ISSUE TITLE
hard skinblur filter seems that  does not work 

### ISSUE THREAD

**Issue by notedit** [lakeinchina/librestreaming#186]
1,  just download the code and have try,  hard skinblur filter seems that  does not work ,  do i miss something?
2, i see there is a rs version skinblur filter,  do you use it inproduction?  is it supported by most devices?

thanks for your amazing work.

**Comment by lakeinchina** [comment]
1.the float posion precision in glsl should be highp, mediump does not work on some devices.I will fix it later.
2.I found no compatibility issues on Limited test devices but I haven't used renderscript in the product.

**Comment by notedit** [comment]
thanks
