### ISSUE TITLE
噪音大，很多情况听不清说话，这个怎么处理呀

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#19]
如题

**Comment by lakeinchina** [comment]
环境噪声?可能有些手机降噪比较好。自己可以用音频滤镜来降噪，具体降噪算法我不清楚。

**Comment by hike2008** [comment]
会是录音时候的采样率之类配置不对么

**Comment by lakeinchina** [comment]
噪声大这个词完全不知道是什么意思，=“我电脑坏了，怎么修？”

**Comment by hike2008** [comment]
现象是, 如果是 非推流手机 放音乐, 在播放时候的声音是ok的, 但是 使用推流手机播放音乐, 就会有杂音, 如果是推流手机说话, 很可能听不清说话了

**Comment by lakeinchina** [comment]
我试的边播放音乐变录没有噪声，是不是你的播放手机和推流手机太近，把播放声音录进去，形成回声了？

**Comment by hike2008** [comment]
感谢回复, 我这边再定位下问题, 然后再请教吧, 目前推测 可能 1, AudioFilter导致; 2, 环境干扰; 3, 录制和播放制式不匹配.

**Comment by lakeinchina** [comment]
可以吧sample,setSoftAudioFilter去掉，屏蔽掉AudioFilter的问题
