### ISSUE TITLE
Error:Execution failed for task ':sample:compileDebugRenderscript'.

### ISSUE THREAD

**Issue by mbpz** [lakeinchina/librestreaming#199]
Error:Execution failed for task ':sample:compileDebugRenderscript'.
> A problem occurred starting process 'command '/home/doug/Android/Sdk/build-tools/26.0.2/arm-linux-androideabi-ld''

**Comment by mbpz** [comment]
compile in Ubuntu 
Warning:Linking two modules of different data layouts: '/home/doug/Android/Sdk/build-tools/26.0.2/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64' whereas '/home/doug/AndroidStudioProjects/librestreaming/sample/build/generated/res/rs/debug/raw/skinblur.bc' is 'e-p:32:32-i64:64-v128:64:128-n32-S64'
Warning:Linking two modules of different target triples: /home/doug/Android/Sdk/build-tools/26.0.2/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'armv7--linux-android' whereas '/home/doug/AndroidStudioProjects/librestreaming/sample/build/generated/res/rs/debug/raw/skinblur.bc' is 'armv7-none-linux-gnueabi'

**Comment by siddharth-shah** [comment]
@DougZeng How did you solve this issue?
