### ISSUE TITLE
Need arm64-v8a to publish on GooglePlay

### ISSUE THREAD

**Issue by udongeex** [lakeinchina/librestreaming#209]
Hello @lakeinchina , I'm using your libs for a long time and my previous app working fine. But lately, GooglePlay publish new policy and require app to support 64 bit as well.
Can you please add arm64-v8a folder with 64 bit.so file ? Thanks you very much

**Comment by udongeex** [comment]
I did try ndk-build, but it generate error here
https://github.com/lakeinchina/librestreaming/issues/142#issuecomment-615962067

**Comment by blagojcoJuca** [comment]
+1

**Comment by lakeinchina** [comment]
solved
