### ISSUE TITLE
了解一下磨皮的地方

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#21]
我想修改磨皮的效果，我看磨皮是使用了一个shader是加载了一个.glsl 的文件，我如何才能进行参数的修改呢？还是需要写多个 shader 但是感觉这样有点变扭啊

**Comment by flyminiboy** [comment]
主要是
const lowp float R = 8.0;
const int iD = 5;
const float maxdelta = 0.06;
这几个参数吗？可以解释一下这几个参数的含义吗？多谢

**Comment by lakeinchina** [comment]
R模糊半径，越大模糊越厉害。
iD步数，循环次数，和R有关。因为gles循环体只支持常量，修改这个只能换shader。
maxdelta阈值，越大磨得越厉害，可以改成uniform来修改值。
你这个是旧的，新的版本优化了性能。

**Comment by flyminiboy** [comment]
iD 和 R 有关系？那这个关系之间有什么规律吗？
还有咨询一下 粉嫩效果是和美白一样修改颜色表呢还是也需要shader

**Comment by lakeinchina** [comment]
新的优化了效率，少计算了3/4个像素，iD＝R+1。
我不清楚粉嫩到底是什么样的效果，盖一张半透明的粉嫩图片就行了吧，就是再组合一个TowInputFilterHard。如果是美白那样的，那就还是颜色表的问题，大概是把所有颜色都向粉色靠近。

**Comment by flyminiboy** [comment]
```
            GLfloat fBeautyParam[4];
            fBeautyParam[0] = 1.0*(1.0-smoothLevel);//磨皮
            fBeautyParam[1] = 1.0*(1.0-whiteLevel*0.5);//提亮（白）
            fBeautyParam[2] = 0.2;//对比度
            fBeautyParam[3] = 1.0*pinkLevel;//变红
            glUniform4fv(m_beautyParam, 1, fBeautyParam);
```

大概是这个样子 那个变红是就粉嫩

**Comment by lakeinchina** [comment]
没看懂贴这段代码的意义，既然你都有美颜的源码了，移植过来是很容易的

**Comment by flyminiboy** [comment]
更新了最新的代码在srs 上面不能观看了  显示的没有帧率 有码率

**Comment by lakeinchina** [comment]
我试的是可以的

**Comment by 307509256** [comment]
请问你的磨皮算法是在底层实现的吗？
可否解释下这段代码

 for(y=0;y<iD;y+=1){
        if (yf < 0.0 || yf > 1.0){
            yf+=yStep;
            continue;
        }
        rowsum.r=0.0;
        rowsum.g=0.0;
        rowsum.b=0.0;
        rowfact.r=0.0;
        rowfact.g=0.0;
        rowfact.b=0.0;
        for(x=0;x<iD;x+=1){
            if (xf < 0.0 || xf > 1.0){
                xf+=xStep;
                continue;
            }
            color2 = texture2D(uCamTexture,vec2(xf,yf));
            tmp = color - color2;
            if (tmp.r < maxdelta && tmp.r > -maxdelta){
                rowsum.r += color2.r;
                rowfact.r +=1.0;
            }
            if (tmp.g < maxdelta && tmp.g > -maxdelta){
                rowsum.g += color2.g;
                rowfact.g +=1.0;
            }
            if (tmp.b < maxdelta && tmp.b > -maxdelta){
                rowsum.b += color2.b;
                rowfact.b +=1.0;
            }
            xf+=xStep;
        }
        sum+=rowsum;
        fact+=rowfact;
        yf+=yStep;
        xf=xfS;
    }
    vec4 res = sum/fact;
    if(fact.r<1.0){
        r = color.r;
    }else{
        r = res.r;
    }
    if(fact.g<1.0){
        g = color.g;
    }else{
        g = res.g;
    }
    if(fact.b<1.0){
        b = color.b;
    }else{
        b = res.b;
    }
    gl_FragColor = vec4(r,g,b,1.0);

**Comment by lakeinchina** [comment]
就是一个带阈值的均值滤波器（其实高斯模糊会更好，只是之前用cpu算为了避免浮点运算就简化了）。
这个和用renderscript实现的skinblur.rs基本一样，你可以看这个，很简单的代码.

**Comment by flyminiboy** [comment]
uniform mediump float maxdelta 这样定义可以通过 GLES20.glUniform1f() 这个对他的值进行赋值吗？

**Comment by flyminiboy** [comment]
我改成上面那种定义直接就奔溃了 maxdelta 这个不能定位为 uniform mediump float 这个类型吗？

**Comment by flyminiboy** [comment]
maxdelta 这个值也在循环体里面了

**Comment by lakeinchina** [comment]
可以，但是我认为我没有义务教你gles着色器语言基础，你可以去参考OpenGLES2.0ProgrammingGuide

**Comment by flyminiboy** [comment]
小白望理解，再问一个问题就是我可以在 ondraw 里面进行颜色表的修改吗？

**Comment by lakeinchina** [comment]
可以，凡是gl的操作都要在onInit，onDraw，onDestroy里面操作，其他的修改在acquireHardVideoFilter和releaseHardVideoFilter之间是安全的。
基本就是在acquireHardVideoFilter和releaseHardVideoFilter之间修改colorMap，在onDraw里通过glTexSubImage2D更新颜色表纹理

**Comment by 307509256** [comment]
作者，能否增加一些注释？  特别是glsl美颜这块，还没完全看懂
java有注释就更好

**Comment by flyminiboy** [comment]
在onDraw 里面更新纹理那个不太明白 不过我用了一个笨方法，更新的时候 和切换进行了一样的操作 这样会不会很伤性能

**Comment by lakeinchina** [comment]
这样当然会伤性能，但是只要调用频率不高也没啥
