### ISSUE TITLE
opengle 底层崩溃

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#22]
请问下有遇到过这个问题吗？
`signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00001004
Stack frame #00  pc 00010514  /system/lib/libc.so (dlmalloc+1207)
Stack frame #01  pc 0000de93  /system/lib/libc.so (malloc+10)
Stack frame #02  pc 001542b0  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #03  pc 0005b8bc  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #04  pc 0005bba8  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #05  pc 0005bc3c  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #06  pc 001114bc  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #07  pc 00111578  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #08  pc 0011c7ec  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #09  pc 0011d4d0  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #10  pc 001075e4  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #11  pc 00107cac  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #12  pc 0013af88  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #13  pc 0005e5e0  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #14  pc 00154e4c  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #15  pc 00194958  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #16  pc 00190870  /system/vendor/lib/egl/libGLES_mali.so
Stack frame #17  pc 00180bf8  /system/vendor/lib/egl/libGLES_mali.so (glLinkProgram+52)
Stack frame #18  pc 0001eb8c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
Stack frame #19  pc 0004f253  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
Stack frame #20  pc 00027fa0  /system/lib/libdvm.so
Stack frame #21  pc 0002f110  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
Stack frame #22  pc 0002c774  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
Stack frame #23  pc 00061705  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
Stack frame #24  pc 00061729  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
Stack frame #25  pc 00056423  /system/lib/libdvm.so
Stack frame #26  pc 0000d408  /system/lib/libc.so (__thread_entry+72)
Stack frame #27  pc 0000d5a0  /system/lib/libc.so (pthread_create+240)
Stack frame #00  pc 00010514  /system/lib/libc.so (dlmalloc+1207) }{stackFuzzy, #00  pc 00010514  /system/lib/libc.so (dlmalloc+1207),#01  pc 0000de93  /system/lib/libc.so (malloc+10),#02  pc 001542b0  /system/vendor/lib/egl/libGLES_mali.so,#03  pc 0005b8bc  /system/vendor/lib/egl/libGLES_mali.so,#04  pc 0005bba8  /system/vendor/lib/egl/libGLES_mali.so,#05  pc 0005bc3c  /system/vendor/lib/egl/libGLES_mali.so,#06  pc 001114bc  /system/vendor/lib/egl/libGLES_mali.so,#07  pc 00111578  /system/vendor/lib/egl/libGLES_mali.so,#08  pc 0011c7ec  /system/vendor/lib/egl/libGLES_mali.so,#09  pc 0011d4d0  /system/vendor/lib/egl/libGLES_mali.so,#10  pc 001075e4  /system/vendor/lib/egl/libGLES_mali.so,#11  pc 00107cac  /system/vendor/lib/egl/libGLES_mali.so,#12  pc 0013af88  /system/vendor/lib/egl/libGLES_mali.so,#13  pc 0005e5e0  /system/vendor/lib/egl/libGLES_mali.so,#14  pc 00154e4c  /system/vendor/lib/egl/libGLES_mali.so,#15  pc 00194958  /system/vendor/lib/egl/libGLES_mali.so,#16  pc 00190870  /system/vendor/lib/egl/libGLES_mali.so,#17  pc 00180bf8  /system/vendor/lib/egl/libGLES_mali.so (glLinkProgram+52),#18  pc 0001eb8c  /system/lib/libdvm.so (dvmPlatformInvoke+112),#19  pc 0004f253  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398),#20  pc 00027fa0  /system/lib/libdvm.so,#21  pc 0002f110  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76),#22  pc 0002c774  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184),#23  pc 00061705  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336),#24  pc 00061729  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20),#25  pc 00056423  /system/lib/libdvm.so,#26  pc 0000d408  /system/lib/libc.so (__thread_entry+72),#27  pc 0000d5a0  /system/lib/libc.so (pthread_create+240) }
Stack frame #00  pc 00010514  /system/lib/libc.so (dlmalloc+1207);#01  pc 0000de93  /system/lib/libc.so (malloc+10);#02  pc 001542b0  /system/vendor/lib/egl/libGLES_mali.so;#03  pc 0005b8bc  /system/vendor/lib/egl/libGLES_mali.so;#04  pc 0005bba8  /system/vendor/lib/egl/libGLES_mali.so;#05  pc 0005bc3c  /system/vendor/lib/egl/libGLES_mali.so;#06  pc 001114bc  /system/vendor/lib/egl/libGLES_mali.so;#07  pc 00111578  /system/vendor/lib/egl/libGLES_mali.so;#08  pc 0011c7ec  /system/vendor/lib/egl/libGLES_mali.so;#09  pc 0011d4d0  /system/vendor/lib/egl/libGLES_mali.so;#10  pc 001075e4  /system/vendor/lib/egl/libGLES_mali.so;#11  pc 00107cac  /system/vendor/lib/egl/libGLES_mali.so;#12  pc 0013af88  /system/vendor/lib/egl/libGLES_mali.so;#13  pc 0005e5e0  /system/vendor/lib/egl/libGLES_mali.so;#14  pc 00154e4c  /system/vendor/lib/egl/libGLES_mali.so;#15  pc 00194958  /system/vendor/lib/egl/libGLES_mali.so;#16  pc 00190870  /system/vendor/lib/egl/libGLES_mali.so;#17  pc 00180bf8  /system/vendor/lib/egl/libGLES_mali.so (glLinkProgram+52);#18  pc 0001eb8c  /system/lib/libdvm.so (dvmPlatformInvoke+112);#19  pc 0004f253  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398);#20  pc 00027fa0  /system/lib/libdvm.so;#21  pc 0002f110  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76);#22  pc 0002c774  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184);#23  pc 00061705  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336);#24  pc 00061729  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20);#25  pc 00056423  /system/lib/libdvm.so;#26  pc 0000d408  /system/lib/libc.so (__thread_entry+72);#27  pc 0000d5a0  /system/lib/libc.so (pthread_create+240); version_number=null`

**Comment by lakeinchina** [comment]
不清楚，我都是在java层用的gl。偶现bug？三星猎户座处理器？

**Comment by jtyang** [comment]
嗯，偶现的，华为荣耀6机器
