### ISSUE TITLE
怎么能把滤镜功能提出来，用在自己的硬编码推流项目里

### ISSUE THREAD

**Issue by lisnstatic** [lakeinchina/librestreaming#23]
作者，我自己有一套mediacodec编码推流的东西，想加上滤镜，请问这个项目里滤镜的功能怎么能加到我的项目里，看了一天没找到头绪

**Comment by lakeinchina** [comment]
这不是两句话说的清的..基本就是RES(Soft/Hard)VideoCore里面的东西
如果是用buffer的方式用MediaCodec就参考软滤镜。如果是以inputsurface的方式就参考硬滤镜。
