### ISSUE TITLE
请问作者，我下载的项目缺少ScriptC_skinblur这个类

### ISSUE THREAD

**Issue by kexuebin** [lakeinchina/librestreaming#24]
请问作者，我下载的项目缺少ScriptC_skinblur.java是怎么回事

**Comment by kexuebin** [comment]
![qq 20160630142536](https://cloud.githubusercontent.com/assets/20219652/16478802/9f463770-3ece-11e6-81be-758251aa6264.png)

**Comment by lakeinchina** [comment]
那个是自动生成的，你的gradle build失败了吧。linux上不要用23，renderscript build失败

**Comment by kexuebin** [comment]
我用的eclipse，麻烦发一个ScriptC_skinblur.java好吗，谢谢，163-400-1299@qq.com

**Comment by lakeinchina** [comment]
额，发了也不能用，还有别的依赖，直接删掉这个filter就行了，不影响使用

**Comment by kexuebin** [comment]
那美颜功能不能用了吧

**Comment by lakeinchina** [comment]
可以用hard模式美颜
