### ISSUE TITLE
GLHelper抛throw new RuntimeException如何处理？简单try..catch?

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#26]
对了，楼主，请问下现在GLHelper里面的很多函数都抛throw new RuntimeException(xxx),如果真出现了异常是不是该处理下，现在没处理程序就直接崩溃了。

**Comment by lakeinchina** [comment]
那里面抛异常八成是不能正常运行了。抛的异常LOG是什么？

**Comment by jtyang** [comment]
java.lang.RuntimeException
eglMakeCurrent,failed:EGL_BAD_NATIVE_WINDOW
在VideoGLThread.cleanUpMedia()执行的时候。

另外，GLESTools的checkGlError（）函数也有可能出运行时异常。

**Comment by lakeinchina** [comment]
cleanUpMedia的时候catch住应该就没事。
GLESTools的异常不行，需要具体日志看一下
