### ISSUE TITLE
关于录屏直播

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#29]
你好，如果在这个架构之上补充录屏直播，请问有什么好的建议和想法。谢谢
先基于5.0就可以，5.0开放了录屏api 。

**Comment by lakeinchina** [comment]
把RESVideoClient换掉，主要是把camera.setPreviewTexture()换成MediaProjection.createVirtualDisplay然后RESCoreParameters的大小参数调整一下，大概就可以了，剩下的应该不用动

**Comment by hike2008** [comment]
这个能在直播中进行两个数据源之间切换么?

**Comment by lakeinchina** [comment]
和前后摄像头切换应该是一个道理，但是不能切换分辨率

**Comment by kexuebin** [comment]
我也也在做这个

**Comment by hezhubo** [comment]
大神，问一下屏幕直播的问题。我把滤镜和摄像头都去掉的，在 RESVideoCore 中传入 MediaProjection 并和 MediaCodec 关联起来了，成功的推送了屏幕数据。但出现问题，打开视频流相当慢（延迟30s以上），并且声音是没有推送成功的，可能是线程调度出问题了，不知道大神有没有解决办法。方便的话加一下我 QQ：526125686，感谢！
