### ISSUE TITLE
如何使用gpuimge进行滤镜处理

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#30]
Demo里面好像并没有类似的可参考的滤镜, 可否说下如何使用,不胜感激

**Comment by lakeinchina** [comment]
SobelEdgeDetectionHardVideoFilter DifferenceBlendFilterHard Base3x3SamplingHardVideoFilter
都是我从gpuimage改过来的，其实很容易。
因为我并不需要使用gpuimage的滤镜，所以也就没使用gpuimage的滤镜架构。。。。也许我可以写个东西用来兼容gpuimage的滤镜代码

**Comment by hike2008** [comment]
嗯, 从gpuimage改过来的大概步骤是怎样的呢, 或者 要兼容gpuimage大概如何操作;

**Comment by lakeinchina** [comment]
初始化操作都放在onInit里面，销毁都放在onDestroy里面，所有的对gl变量设值的操作需要先暂存一下，然后到onDraw的时候再设到gl里面。然后就是draw的时候需要绘制到targetFrameBuffer上面，就是绘制之前绑定一下这个帧缓存。
它的shader的position和inputTextureCoordinate要用shapeBuffer和textrueBuffer来填值。
最后就是绘制要用GLES20.glDrawElements(***, drawIndecesBuffer);
大概是这样吧，我改的时候领会了一下算法，然后再改过来的。。

**Comment by hike2008** [comment]
好的, 谢谢, 我这边试试看

**Comment by lakeinchina** [comment]
现在已经可以兼容GPUImage的滤镜了，一行代码都不用改
