### ISSUE TITLE
磨皮奔溃

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#31]
更新最新代码以后，推流的时候进行磨皮的时候出现闪退的情况
魅蓝note

**Comment by lakeinchina** [comment]
有日志吗?

**Comment by flyminiboy** [comment]
java.lang.RuntimeException

fragment shader compile,failed:0:37: S0001: No matching overload for function 'abs' found
me.lake.librestreaming.tools.GLESTools.createProgram(GLESTools.java:57)
me.lake.librestreaming.filter.hardvideofilter.OriginalHardVideoFilter.onInit(OriginalHardVideoFilter.java:47)
me.lake.librestreaming.sample.hardfilter.SkinBlurHardVideoFilter.onInit(SkinBlurHardVideoFilter.java:101)
me.lake.librestreaming.core.RESHardVideoCore$VideoGLThread.drawFrameBuffer(RESHardVideoCore.java:417)
me.lake.librestreaming.core.RESHardVideoCore$VideoGLThread.run(RESHardVideoCore.java:319)

**Comment by flyminiboy** [comment]
还有一个问题就是我发现从播放器看到的内容要比预览里面的内容要多一点

**Comment by lakeinchina** [comment]
内置函数兼容问题，fix了。
现在的AspectTextureView模式MODE_OUTSIDE是为了保证比例占满空间的模式，所以如果比例不匹配就会截取一些。MODE_INSIDE是保证比例留黑边。MODE_FITXY是拉伸比例沾满空间。

**Comment by flyminiboy** [comment]
好了，这种模式的磨皮我想调整磨皮的级别 调整那个参数呢？

**Comment by lakeinchina** [comment]
stepScale参数我已经拿出来了，还有就是之前的maxdelta

**Comment by flyminiboy** [comment]
这俩个参数在取值的时候，有没有一定的范围 ，还有他们之间的取值会相互影响吗？

**Comment by lakeinchina** [comment]
没影响，stepScale就是1，2，3，4..这样取，maxdelta就是0.0-1.0

**Comment by flyminiboy** [comment]
stepScale 这个参数控制的是磨皮的那个因素呢？

**Comment by lakeinchina** [comment]
采样范围，越大磨的越厉害

**Comment by flyminiboy** [comment]
如果我想通过软编码实现美白/粉嫩是不是参考 GrayFilterSoft 这个就可以？软编码的磨皮是不是通过控制
int delta = 18;
int radius = (int) (6 + 1.0);
int numrad = (int) (radius + 1.0);
这几个参数实现 磨皮的等级？ 他们之前有什么联系吗？

**Comment by flyminiboy** [comment]
更正一下是软模式 还有硬模式

**Comment by lakeinchina** [comment]
和之前你问的硬滤镜一样的，delta＝maxdelta*256.radius，numrad和R，iD对应。软滤镜浮点计算太慢了，我不打算维护软滤镜了

**Comment by flyminiboy** [comment]
不维护了啊  
因为我是写好了编码推流是用的buffer mediacodec 我看这个是直接对应是软模式的！

**Comment by lakeinchina** [comment]
因为硬模式的美颜浮点运算变多了，估计算不过来了。
这个调参数就是delta和radius可以调，越大越慢

**Comment by flyminiboy** [comment]
使用软模式那个v8的包是这么导入的呢？

**Comment by flyminiboy** [comment]
上面那个解决了
ScriptC_skinblur 这个在哪里啊

**Comment by lakeinchina** [comment]
编译的时候自动生成的

**Comment by flyminiboy** [comment]
软模式的美白/粉嫩的实现可以指点一下吗？

**Comment by lakeinchina** [comment]
每个像素都和粉色alpha混合一下，大概就行吧

**Comment by flyminiboy** [comment]
你实现的里面又可以参考的吗？

**Comment by lakeinchina** [comment]
没有

**Comment by flyminiboy** [comment]
好像软模式里面么有多个滤镜叠加到一起的那个类型吧

**Comment by lakeinchina** [comment]
没有，但是把算法写在一个滤镜里面就好了，一样的效果

**Comment by flyminiboy** [comment]
public boolean onFrame(byte[] orignBuff, byte[] targetBuff, long presentationTimeMs, int sequenceNum) 
我应该在这个回调里面对targetBuff 这个进行处理就可以吧

**Comment by lakeinchina** [comment]
orignBuff是原始数据，可以直接修改，也可以把数据填到targetBuff。
修改orignBuff就返回false，填充targetBuff就返回true

**Comment by flyminiboy** [comment]
我现在数据是已经处理好（格式转换，翻转，缩放）的是不是就不需要在RESSoftVideoCore里面再进行转换； 只需要添加滤镜整一个操作就行，然后再把得到的数据用过我之前的传输出去就行了

**Comment by lakeinchina** [comment]
对

**Comment by flyminiboy** [comment]
推流 观看的时候语音播放好像是快进了 你有遇到吗？

**Comment by lakeinchina** [comment]
soft模式，低端手机，滤镜很耗时的情况下，缓冲会被挤满，因为图像帧有5帧的缓冲，如果视频只剩10帧了，那么会有0.5秒的音画不同步。
可以把这个帧缓冲调小，RESConfig.setVideoBufferQueueNum

**Comment by flyminiboy** [comment]
hard 模式 音频还想也是有问题  隆隆那样的

**Comment by flyminiboy** [comment]
colormixfilter 这个是不是可以替换whiteing这个啊？

**Comment by flyminiboy** [comment]
那个声音应该是 使用flash播放的时候出现的问题

**Comment by lakeinchina** [comment]
音频问题不知道怎么回事，也没遇到过，也许是音量滤镜的问题，可以注释掉

**Comment by flyminiboy** [comment]
注释了 还是不行。可能是播放器的问题，你那边观看播放用是flash播放器吗？

**Comment by lakeinchina** [comment]
三端都有，没有这种问题
