### ISSUE TITLE
web端观看推流会有卡顿现象

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#32]
测试过程中，web端观看推流，有的手机会load圈一卡一卡的。pc推是正常的 网络环境一致。
如果我调试配置的话，是不是应该考虑以下几点就可以了。
bitRate 码率（图像质量）
framerate 帧率 （画面流畅度）
另外，推流的过程中，不会有延时阻塞等情况吧，请指点，谢谢。

**Comment by lakeinchina** [comment]
卡顿的话，除了网络引起的卡顿，我只发现过由于手机太慢帧率太低(<10)的时候某些播放器会卡顿。
内部所有的参数都在RESCoreParameters里面。
主要影响延迟的是senderQueueLength，是发包的缓冲，默认150，可以修改。如果网速不够，缓冲越长延迟越高。满了那就有秒级的延迟。
mediacdoecAVCBitRate是码率，可以用RESConfig来设。
previewMaxFps，previewMinFps是帧率，取决于手机，不能随便设。CameraHelper会选一个最接近（targetFps = 30000）的帧率范围。
