### ISSUE TITLE
6.0系统问题

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#33]
有个问题就是6.0系统 打开摄像头失败。

**Comment by lakeinchina** [comment]
基本是权限问题，6.0以上activity代码里要再申请摄像头权限

**Comment by androidwzq** [comment]
6.0以上的系统录音和摄像头权限的确得特殊处理下。
ActivityCompat.checkSelfPermission(this, Manifest.permission.CAMERA)
 ActivityCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO)

 ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.CAMERA , Manifest.permission.RECORD_AUDIO},
                    permsRequestCode);

已解决，谢谢。
