### ISSUE TITLE
lenovo x2-TO问题

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#34]
部分手机，比如lenovo x2-TO这款
videoSenderThread = new VideoSenderThread("VideoSenderThread", dstVideoEncoder, flvDataCollecter);
                videoGLThread = new VideoGLThread(camTex, dstVideoEncoder.createInputSurface(), currentCamera);
                dstVideoEncoder.start();
                videoSenderThread.start();
                videoGLThread.start();
通过过滤代码 测试结果，以上代码会导致卡死，应用无响应。不知道为何，希望能帮分析下，谢谢
大部分手机没有该问题，不过也有小概率事件会卡死。无响应。

**Comment by lakeinchina** [comment]
我目前还从来没遇到过这种情况

**Comment by lakeinchina** [comment]
我目前还从来没遇到过这种情况
