### ISSUE TITLE
音频来源获取

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#36]
如果手机连接了蓝牙耳机 如何设置声音来源是从蓝牙耳机的麦克风处获取呢？

**Comment by lakeinchina** [comment]
大概是修改RESAudioClient里面resCoreParameters.audioRecoderSource = MediaRecorder.AudioSource.DEFAULT;

**Comment by flyminiboy** [comment]
美白那个我想把你那个 0.7的系数提取出来 进行动态的修改是不是就不能按照现在这样写了

**Comment by lakeinchina** [comment]
如果要动态修改，需要在修改的时候重新算colorMap,然后在onDraw的时候去更新imageTexture，shader不用改。
现在兼容gpuimage滤镜了，不知道它有没有美白的

**Comment by flyminiboy** [comment]
没有美白，我重新计算了colormap
然后在ondraw 里面用 glTexSubImage2D 这个修改的，但是直接奔溃了。在 GLES20.glViewport(0, 0, SIZE_WIDTH, SIZE_HEIGHT); 这句代码前面调用的
GLES20.glTexSubImage2D(GLES20.GL_TEXTURE_2D, 0, 0, 0, 256, 1, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, result);

**Comment by flyminiboy** [comment]
是在 acquireHardVideoFilter 和 releaseHardVideoFilter 中间进行的操作

**Comment by lakeinchina** [comment]
你可以把那段代码完整的贴出来

**Comment by flyminiboy** [comment]
public void setRatio(float ratio) {
        mRatio = ratio;
        if (colorMap != null) {
            colorMap = null;
        }
        colorMap = new byte[1024];
        int cur = -1;
        for (int i = 0; i < 256; i++) {
            colorMap[++cur] = ((byte) (int) (255 \* Math.pow(i / 255.0, mRatio)));
            colorMap[++cur] = ((byte) (int) (255 \* Math.pow(i / 255.0, mRatio)));
            colorMap[++cur] = ((byte) (int) (255 \* Math.pow(i / 255.0, mRatio)));
            colorMap[++cur] = 0;
        }
        flag = true;
    }
这是在acquireHardVideoFilter 和 releaseHardVideoFilter 中间调用的代码

```
    GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER, targetFrameBuffer);
    GLES20.glUseProgram(glProgram);
    GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, cameraTexture);
    GLES20.glUniform1i(glCamTextureLoc, 0);
    GLES20.glActiveTexture(GLES20.GL_TEXTURE1);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, imageTexture);
    GLES20.glUniform1i(glColorMapTextureLoc, 1);
    GLES20.glEnableVertexAttribArray(glCamPostionLoc);
    GLES20.glEnableVertexAttribArray(glCamTextureCoordLoc);
    shapeBuffer.position(0);
    GLES20.glVertexAttribPointer(glCamPostionLoc, 2,
            GLES20.GL_FLOAT, false,
            2 * 4, shapeBuffer);
    textrueBuffer.position(0);
    GLES20.glVertexAttribPointer(glCamTextureCoordLoc, 2,
            GLES20.GL_FLOAT, false,
            2 * 4, textrueBuffer);

    if (flag) {
        ByteBuffer result = ByteBuffer.allocateDirect(colorMap.length).
                order(ByteOrder.nativeOrder());
        result.position(0);
        result.put(colorMap);
        GLES20.glTexSubImage2D(GLES20.GL_TEXTURE_2D, 0, 0, 0, 256, 1, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, result);
        flag = false;
    }

    GLES20.glViewport(0, 0, SIZE_WIDTH, SIZE_HEIGHT);
    GLES20.glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
    GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT);
    GLES20.glDrawElements(GLES20.GL_TRIANGLES, drawIndecesBuffer.limit(), GLES20.GL_UNSIGNED_SHORT, drawIndecesBuffer);
    GLES20.glFinish();
    GLES20.glDisableVertexAttribArray(glCamPostionLoc);
    GLES20.glDisableVertexAttribArray(glCamTextureCoordLoc);
    GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, 0);
    GLES20.glUseProgram(0);
    GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER, 0);
```

onDraw 里面的代码

**Comment by lakeinchina** [comment]
result.put(colorMap);
后面加个
result.position(0);

**Comment by flyminiboy** [comment]
可以了 多谢
