### ISSUE TITLE
音频音量的控制

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#39]
VolumeAudioFilter 这个过滤器可以实现非音量的控制 ，控制范围是0-无限大吗？
还有 设置多少的时候 音量是默认采集到的音量呢？

**Comment by lakeinchina** [comment]
默认1，5就是放大5倍

**Comment by flyminiboy** [comment]
快速切换前后置摄像头 会有卡顿的问题

**Comment by lakeinchina** [comment]
没听懂

**Comment by flyminiboy** [comment]
翻转摄像头 界面会卡 而且有时候会出现一个倒立的画面   而且有时候会回调到 onWriteError

**Comment by lakeinchina** [comment]
会卡是因为camera。open很慢

**Comment by flyminiboy** [comment]
BufferQueue: [unnamed-17273-4] queueBuffer: BufferQueue has been abandoned!
切换时候会有这个  然后预览就失败了

**Comment by flyminiboy** [comment]
BufferQueue: [unnamed-17273-4] queueBuffer: BufferQueue has been abandoned!
 俩个没有关系 应该是在onwriteerror 里面stop了  切换摄像头的时候有时候会写数据失败

**Comment by flyminiboy** [comment]
BufferQueue: [unnamed-17273-4] queueBuffer: BufferQueue has been abandoned! 
stop 的时候 有遗漏 相机stoppreview 和释放的操作
