### ISSUE TITLE
硬解码版本推流不成功

### ISSUE THREAD

**Issue by testllg** [lakeinchina/librestreaming#4]
硬解码版本推流不成功，一直出现error，然后卡死。以前的软解码版本推流没有问题。 因为想把gpuimage的滤镜放进来，希望能解决下推流的问题，多谢。

**Comment by lakeinchina** [comment]
手机型号和Log？

**Comment by testllg** [comment]
手机是联想x2-To,  问题是：硬编码第一次开始推流没问题，stop之后再推，界面上会出现writeError,数字一直增加，看了下日志好像是写文件出错。

06-03 12:14:51.969 828-848/? E/ActivityManager: writeStringToFile error: /sys/kernel/debug/binder/transaction_log_enable java.io.FileNotFoundException: /sys/kernel/debug/binder/transaction_log_enable: open failed: EACCES (Permission denied)
06-03 12:14:56.691 248-28146/? E/MDP: DpIsp: 0xb7fa1220, mode -1208343320, dst0 54 ms
06-03 12:15:02.972 828-848/? E/ANRManager: ANR in me.lake.librestreaming.sample (me.lake.librestreaming.sample/.HardStreamingActivity)
                                           Reason: Input dispatching timed out (Waiting because the touched window has not finished processing the input events that were previously delivered to it.)
                                           Load: 15.33 / 16.4 / 16.53
                                           Android time :[2016-06-03 12:15:02.964] [9406.795]
                                           CPU usage from 0ms to 10970ms later:
                                             57% 248/mediaserver: 30% user + 27% kernel / faults: 438 minor
                                             30% 25018/logcat: 10% user + 20% kernel / faults: 6629 minor
                                             25% 27998/me.lake.librestreaming.sample: 14% user + 11% kernel / faults: 141 minor 2 major
                                             22% 306/adbd: 1.4% user + 21% kernel / faults: 15301 minor
                                             18% 828/system_server: 10% user + 7.3% kernel / faults: 700 minor
                                             4.9% 24703/kworker/0:1: 0% user + 4.9% kernel
                                             3.9% 243/surfaceflinger: 1.1% user + 2.7% kernel
                                             2.9% 2935/com.lenovo.calendar: 1.8% user + 1% kernel
                                             2.1% 970/com.android.systemui: 1.7% user + 0.4% kernel / faults: 153 minor
                                             2% 4631/kworker/2:2: 0% user + 2% kernel
                                             2% 24702/kworker/1:0: 0% user + 2% kernel
                                             0.5% 1177/com.android.phone: 0.3% user + 0.1% kernel / faults: 93 minor
                                             1% 4181/kworker/3:2: 0% user + 1% kernel
                                             0.1% 919/com.android.keyguard: 0.1% user + 0% kernel / faults: 121 minor
                                             0.5% 1458/com.qihoo.daemon: 0.2% user + 0.2% kernel / faults: 4 minor
                                             0.4% 50/cfinteractive: 0% user + 0.4% kernel
                                             0% 1308/android.process.acore: 0% user + 0% kernel / faults: 101 minor
                                             0.4% 4009/com.tencent.android.qqdownloader: 0.3% user + 0% kernel / faults: 26 minor 1 major
                                             0% 1284/com.lenovo.weatherserver: 0% user + 0% kernel / faults: 134 minor
                                             0.2% 3/ksoftirqd/0: 0% user + 0.2% kernel
                                             0.2% 124/mtk charger_hv_: 0% user + 0.2% kernel
                                             0.2% 802/gsm0710muxd: 0% user + 0.2% kernel
                                             0% 931/com.lenovo.gesture: 0% user + 0% kernel / faults: 104 minor
                                             0.2% 967/hif_thread: 0% user + 0.2% kernel
                                             0% 1189/com.lenovo.runtime: 0% user + 0% kernel / faults: 107 minor
                                             0.1% 1215/com.lenovo.lenovosmartscene: 0% user + 0% kernel / faults: 86 minor
                                             0% 1227/com.lenovo.lightsettings: 0% user + 0% kernel / faults: 117 minor
                                             0% 1249/com.mediatek.nlpservice: 0% user + 0% kernel / faults: 137 minor
                                             0% 1274/com.lenovo.smartrotation: 0% user + 0% kernel / faults: 101 minor
                                             0% 1326/com.android.incallui: 0% user + 0% kernel / faults: 112 minor
                                             0.1% 8/rcu_preempt: 0% user + 0.1% kernel
                                             0.1% 116/mmcqd/0: 0% user + 0.1% kernel
                                             0.1% 857/ksdioirqd/mmc1: 0% user + 0.1% kernel
                                             0% 1079/com.amap.android.location: 0% user + 0% kernel / faults: 87 minor
                                             0% 1201/com.mediatek.bluetooth: 0% user + 0% kernel / faults: 96 minor
                                             0.1% 1239/com.lenovo.widetouch: 0.1% user + 0% kernel / faults: 100 minor
                                             0% 1256/com.lenovo.wifiswitch: 0% user + 0% kernel / faults: 98 minor
                                             0% 4107/com.tencent.android.qqdownloader:connect: 0% user + 0% kernel / faults: 27 minor
                                             0.1% 27677/kworker/0:0: 0% user + 0.1% kernel
                                             0% 1//init: 0% user + 0% kernel
                                             0% 55/hps_main: 0% user + 0% kernel
                                             0% 110/fence_worker: 0% user + 0% kernel
                                             0% 123/bat_thread_kthr: 0% user + 0% kernel
                                             0% 184/jbd2/mmcblk0p15: 0% user + 0% kernel
                                             0% 223/healthd: 0% user + 0% kernel
                                             0% 235/debuggerd: 0% user + 0% kernel / faults: 52 minor
                                             0% 858/stp_sdio_tx_rx: 0% user + 0% kernel
                                             0% 966/tx_thread: 0% user + 0% kernel
                                             0% 1681/com.qihoo.gameassist: 0% user + 0% kernel / faults: 14 minor
                                             0% 1844/com.lenovo.safecenter: 0% user + 0% kernel / faults: 9 minor
                                             0% 3082/com.lenovo.ue.service: 0% user + 0% kernel
                                             0% 23583/kworker/u16:1: 0% user + 0% kernel
                                             0% 24631/kworker/u16:0: 0% user + 0% kernel
                                             0% 27987/kworker/u17:2: 0% user + 0% kernel
                                           0.4% TOTAL: 0.1% user + 0.2% kernel + 0% softirq
06-03 12:15:02.976 828-848/? E/ActivityManager: get crashInfo fail.
06-03 12:15:03.099 970-970/? E/MyTag: updateClock : 12:15
06-03 12:15:03.117 970-970/? E/MyTag: updateClock : 12:15 中午
06-03 12:15:03.169 970-970/? E/MyTag: updateClock : 12:15 中午
06-03 12:15:03.173 828-844/? E/CubicBezierInterpolator: ####:PointF(0.1, 0.8)
06-03 12:15:03.173 828-844/? E/CubicBezierInterpolator: ####:PointF(0.5, 1.0)
06-03 12:15:03.181 1339-1339/? E/ActionIcon: time changed: time = 20160603T121503Asia/Shanghai(5,154,28800,0,1464927303)
06-03 12:15:18.501 1227-1227/? E/setGreenLight: status=4
06-03 12:15:38.490 1227-1227/? E/setGreenLight: status=4
06-03 12:15:40.517 1415-2011/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:15:40.581 1458-1458/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:15:40.590 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:15:40.628 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:15:48.495 1227-1227/? E/setGreenLight: status=4
06-03 12:16:00.021 970-970/? E/MyTag: updateClock : 12:16
06-03 12:16:00.040 970-970/? E/MyTag: updateClock : 12:16 中午
06-03 12:16:00.080 970-970/? E/MyTag: updateClock : 12:16 中午
06-03 12:16:00.091 1339-1339/? E/ActionIcon: time changed: time = 20160603T121600Asia/Shanghai(5,154,28800,0,1464927360)
06-03 12:16:18.509 1227-1227/? E/setGreenLight: status=4
06-03 12:16:28.558 1227-1227/? E/setGreenLight: status=4
06-03 12:16:40.500 1415-2011/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:16:40.534 1458-1458/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:16:40.579 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:16:40.621 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:16:58.512 1227-1227/? E/setGreenLight: status=4
06-03 12:17:00.018 970-970/? E/MyTag: updateClock : 12:17
06-03 12:17:00.028 970-970/? E/MyTag: updateClock : 12:17 中午
06-03 12:17:00.056 970-970/? E/MyTag: updateClock : 12:17 中午
06-03 12:17:00.070 1339-1339/? E/ActionIcon: time changed: time = 20160603T121700Asia/Shanghai(5,154,28800,0,1464927420)
06-03 12:17:40.496 1415-2011/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:17:40.564 1458-1458/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:17:40.583 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:17:40.633 828-828/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
06-03 12:17:48.504 1227-1227/? E/setGreenLight: status=4

**Comment by lakeinchina** [comment]
别的手机也是一样的表现吗？推流服务器是什么？你试一下soft模式，看看是不是也有问题。我是没有做文件操作的。

**Comment by lakeinchina** [comment]
搞定了？@llg3footcat
