### ISSUE TITLE
马赛克

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#40]
我自己精简了部分代码去掉了软模式滤镜推流发现画面马赛克比较严重，你知道可能是那部分出问题了吗？
skinblur.rs这个文件不是软模式才需要？

**Comment by lakeinchina** [comment]
skinblur.rs软模式滤镜用的

**Comment by flyminiboy** [comment]
额 马赛克是由于我码率设设置参数传递的问题造成的。。。
