### ISSUE TITLE
切换摄像头重连

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#41]
三星S4 切换摄像头的时候 会触发重连

**Comment by flyminiboy** [comment]
我想把 预览和推流分离开 能指点一个着手的方向吗？

**Comment by flyminiboy** [comment]
java.lang.RuntimeException
eglSwapBuffers,failed!

1 me.lake.librestreaming.core.DWVideoCore$VideoGLThread.drawScreen(DWVideoCore.java:480)
2 me.lake.librestreaming.core.DWVideoCore$VideoGLThread.run(DWVideoCore.java:315)

偶现的直接catch可以吗？

**Comment by lakeinchina** [comment]
如果只出现一次后面正常就catch，如果连续出错不行。
