### ISSUE TITLE
请问, 对于降噪, 和 消除回声, 有什么好的建议

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#43]
官方在高版本提供了Api, 但是感觉没什么效果;  借助开源的, 搜索发现 一般是基于webrtc和speex来做, 但是资料实在比较少, 可否指点一二;

**Comment by lakeinchina** [comment]
我也没做过这个，但是speex它们都是对pcm进行处理，在音频滤镜里面用他们对原始音频进行处理应该就行吧

**Comment by hike2008** [comment]
en , 我试试看
