### ISSUE TITLE
推流发热问题

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#45]
推流发热比较严重, 不知道是什么问题, 从什么地方着手优化呢?

**Comment by lakeinchina** [comment]
surface+MediaCodec大概是android上推流效率最高的方案了，要么就降低效果比如降低帧率什么的

**Comment by hike2008** [comment]
这个效果和帧率, 是和通常的推流SDK类似么, 一般推流SDK都有分辨率对应帧率的推荐值, 不知道这个库有没对应的匹配关系呢

**Comment by lakeinchina** [comment]
现在只是会设一个接近30帧的帧率范围，没做设置帧率的功能，因为安卓手机各种机型相机帧率都不一样，只能自己去把这个设备帧率调整到目标帧率，比较麻烦
