### ISSUE TITLE
前直摄像头镜像

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#46]
使用前置摄像头进行推流，在观看的时候，画面镜像效果，想对数据进行一次翻转在那个地方处理呢？

**Comment by lakeinchina** [comment]
resConfig.setFrontCameraDirectionMode

**Comment by flyminiboy** [comment]
=只需要设置设个就行吗？ 预览界面不需要改变只是推出去的时候在观看的时候需要进行一次翻转

**Comment by lakeinchina** [comment]
预览不用变？预览和观看是一样的，翻转了就都翻转了

**Comment by flyminiboy** [comment]
想实现和 手机本身录像那样一样  录制的过程是镜像的效果！但是观看的不要镜像效果，类似映客那样的效果吧！我在哪里可以拿到 采集得到的数据呢 我进行一次翻转再传递出去 应该就可以

**Comment by lakeinchina** [comment]
那这要改源码了，你用的soft还是hard

**Comment by flyminiboy** [comment]
hard 
我试过 在 VideoSenderThread 修改 bytebuffer 没有成功 不知道需要注意什么

**Comment by lakeinchina** [comment]
那个是编码后的数据不能动。
改RESHardVideoCore里面mediaCodecTextureVerticesBuffer的值，参考getCamera2DTextureVerticesBuffer里面的翻转

**Comment by flyminiboy** [comment]
多谢 我去修改一下试试

**Comment by flyminiboy** [comment]
我看那个flip是一个上下翻转我想左右翻转 那个方法可以指点一下怎么处理吗、

**Comment by lakeinchina** [comment]
你的代码里面没有FLAG_DIRECTION_FLIP_HORIZONTAL？

**Comment by flyminiboy** [comment]
有  我现在处理出来的数据 是上下倒了

**Comment by flyminiboy** [comment]
是不是 可以通过 修改 Cam2dTextureVertices_90 这些信息啊  我现在用的就是你写的源码里面的

**Comment by lakeinchina** [comment]
FLAG_DIRECTION_FLIP_HORIZONTAL不行就试试FLAG_DIRECTION_FLIP_VERTICAL

**Comment by lakeinchina** [comment]
算了，直接把MediaCodecTextureVertices[] = {
            0.0f, 1.0f,
            0.0f, 0.0f,
            1.0f, 0.0f,
            1.0f, 1.0f};
改成MediaCodecTextureVertices[] = {
            1.0f, 1.0f,
            1.0f, 0.0f,
            0.0f, 0.0f,
            0.0f, 1.0f};
