### ISSUE TITLE
30.30 fps

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#52]
fps可以进行设置么, 现在这个有点高; IOS端使用时大概是设置在25左右的

**Comment by flyminiboy** [comment]
可以自己指定的 MediaCodec指定参数

**Comment by hike2008** [comment]
在哪儿设置呢,  好像  一般情况是 : (帧率：FPS <=10 会明显感觉到卡顿，但也并不是越高越好，一般推荐是20FPS即可达到很流畅的效果。)

而且 腾讯云 有这个描述:

Android推流为何达不到30FPS

如果您在Android平台上通过setVideoFPS设置帧率为30，可能会发现实际帧率只有20FPS，这是因为:

大部分安卓机器的Camera接口无法实现30FPS及以上的数据采集频率，尤其是前置摄像头。
Android的降频策略在通常状态下只会发挥CPU一半的性能，所以较高的分辨率会出现编码跟不上的情况，也就是即使采集帧率足够了，编码帧率也无法达到。（后续放开硬件编码来解决）
在iPhone 6 及以上机型，通过硬件编码确实可以轻松实现30FPS以上的高清视频编码，但相应的码率输出也会比较高。

**Comment by hike2008** [comment]
resCoreParameters.mediacodecAVCFrameRate

**Comment by hike2008** [comment]
目前 某些摄像头好像会出现类似波浪的虚影, 不知道是不是fps太高导致的

**Comment by lakeinchina** [comment]
MediaCodec的参数不控制帧率

**Comment by hike2008** [comment]
那我要如何修改, 将帧率降下来呢

**Comment by lakeinchina** [comment]
现在没有调帧率的功能，只能调CameraHelper.targetFps

**Comment by flyminiboy** [comment]
这个不是通过这个得到一个范围吗？ 参数那个是一个设置，但是具体的要看机型？

**Comment by lakeinchina** [comment]
那个参数是看机型支持，后面会增加手动设帧率
