### ISSUE TITLE
切换摄像头卡住

### ISSUE THREAD

**Issue by skybdemq** [lakeinchina/librestreaming#55]
HI，lakeinchina
我刚更新了代码，摄像头切换时直接卡住了，更新之前切换不会卡住不动。
之前切换摄像头出现的问题是画面会一瞬间显示180度，然后切换到另一个摄像头的画面正常显示。
请问这是什么原因，怎样修复

切换卡住的log:
ample D/RESLog: RESClient,swapCamera()
08-24 18:57:47.610 30404-30404/me.lake.librestreaming.sample D/RESLog: RESClient,swapCamera()
08-24 18:57:47.638 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692786
08-24 18:57:47.688 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692785
08-24 18:57:47.734 30404-30418/me.lake.librestreaming.sample W/Camera-JNI: callback on dead camera object
08-24 18:57:47.736 30404-30418/me.lake.librestreaming.sample W/Camera-JNI: callback on dead camera object
08-24 18:57:47.738 30404-30418/me.lake.librestreaming.sample W/Camera-JNI: callback on dead camera object
08-24 18:57:47.741 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692788
08-24 18:57:47.939 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692786
08-24 18:57:47.988 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692785
08-24 18:57:48.038 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692786
08-24 18:57:48.089 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692786
08-24 18:57:48.590 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:48.640 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:49.039 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:49.090 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:49.139 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692786
08-24 18:57:50.090 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:50.140 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:50.189 30404-32562/me.lake.librestreaming.sample D/RESLog: VideoFilterHandler,ProcessTime:1472019692787
08-24 18:57:50.208 30404-30404/me.lake.librestreaming.sample D/RESLog: queueVideo,accept ,targetIndex1
08-24 18:57:50.211 30404-30404/me.lake.librestreaming.sample I/Choreographer: Skipped 155 frames!  The application may be doing too much work on its main thread.

**Comment by lakeinchina** [comment]
soft模式？

**Comment by skybdemq** [comment]
是的，hard模式卡1、2秒可以切换，但有我说的第二个问题，我用小米平板2，另一部华为也一样

**Comment by lakeinchina** [comment]
第一个是setCurrCamera.removeCallbacksAndMessages的问题，明天修下。第二个不是很好解决，本质上是切换的时候分不清图像到底是前置还是后置的

**Comment by skybdemq** [comment]
好的，刚更新了代码，卡住不动不问题已经解决，谢谢
