### ISSUE TITLE
华为手机推流, 其他手机观看可能 导致花屏

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#59]
iOS的播放器花屏尤其明显(半屏绿色花屏), Android的的有有类似掉帧的花屏(程度跟网络有关)

**Comment by lakeinchina** [comment]
带宽不足会导致丢帧，播放的时候就会花屏和卡顿

**Comment by hike2008** [comment]
华为推流, iOS端网络比较好的情况下也是会半屏绿色花屏的

**Comment by hike2008** [comment]
可否有更方便的联系方式哈, 不骚扰, 只空的时候请教问题

**Comment by lakeinchina** [comment]
你可以把qq发我邮箱lakeinchina@hotmail.com
