### ISSUE TITLE
分辨率

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#60]
我把TextureView的mode 设置为 MODE_OUTSIDE 如何做到预览（屏幕显示的）和观看的内容一致。
现在问题观看的要比屏幕里面呈现的预览内容要多。

**Comment by lakeinchina** [comment]
设成MODE_INSIDE

**Comment by flyminiboy** [comment]
MODE_INSIDE 在预览界面有黑边 不想要黑边。
我现在是设置TextureView 的尺寸是手机屏幕尺寸，比如1920 \* 1080 在编码的时候我设置为640*360保证比例一致，但是在个别手机会出现观看花屏的问题。

**Comment by lakeinchina** [comment]
所以你要”预览不能留黑边，播放可以留黑边，不能拉伸“？那就只能率一个和现实窗口一样比例的视频。
那这个问题实际是个别手机播放会花屏的问题

**Comment by flyminiboy** [comment]
对是这样的，我保证比例一致实现了 预览没有黑边，预览和播放不拉伸了，但是个别手机推出去的流 在播放的时候 会花屏。所以我想设置一个设备支持的分辨率。

**Comment by flyminiboy** [comment]
我看了一下 大多数设备都支持  640 \* 480 所以想设置这个分辨率，然后mode为 MODE_OUTSIDE 时保证预览没有黑边，播放也正常，但是会出现 播放的内容比预览（屏幕呈现）的内容要多。要是可以把多的内容裁剪了就好了

**Comment by lakeinchina** [comment]
那在播放的时候用相当于MODE_OUTSIDE的策略就行了，把显示内容超出窗口，就会裁剪掉多余的内容
