### ISSUE TITLE
建议：推流时增加动态切换码率功能

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#61]
@lakeinchina 请问下在VideoGLThread如果想在推流过程中把新的Mediacodec input surface设置进去该咋整呢？

**Comment by lakeinchina** [comment]
用新的代码把，改成了VideoGLHandler

**Comment by jtyang** [comment]
嗯，thanks！

**Comment by lakeinchina** [comment]
现在可以动态切换码率了，4.4以上有api可以动态修改
