### ISSUE TITLE
关于 minSdkVersion 18 的问题

### ISSUE THREAD

**Issue by daweibayu** [lakeinchina/librestreaming#63]
看到 lib 中 minSdkVersion 为 18，请问这个限制是有哪些库导致的？
如果想降到 14 的话有什么推荐方式么？谢谢

**Comment by lakeinchina** [comment]
mediacodec是16出来的，所以不可能降到14。hard模式需要用createInputSurface是18出来的也不能用。
综上，soft也许可以降到16。
建议用app需要的sdkversion去编译，在应用中限制>API18的才能使用这个功能。
如果非要兼容到14，那只能用ffmpeg，性能会很差。

**Comment by daweibayu** [comment]
了解，感谢反馈。另外，试用了 librestreaming，很赞。
