### ISSUE TITLE
请问下如何实现手机屏幕的直播？

### ISSUE THREAD

**Issue by rockscy** [lakeinchina/librestreaming#64]
你好，想问下有什么方案实现手机屏幕的直播呢？

**Comment by lakeinchina** [comment]
之前有人问过 #29
android 5.0以上有系统API很容易，必须用hard模式。
先要在activity里面获取到mediaProjection，然后传给RESVideoClient
RESVideoClient大概这样该：
private boolean startVideo() {
camTexture = new SurfaceTexture(RESVideoCore.OVERWATCH_TEXTURE_ID);
camTexture.setDefaultBufferSize(resCoreParameters.videoWidth,resCoreParameters.videoHeight);
        surface = new Surface(camTexture);
            camTexture.setOnFrameAvailableListener(new SurfaceTexture.OnFrameAvailableListener() {
                @Override
                public void onFrameAvailable(SurfaceTexture surfaceTexture) {
                    synchronized (syncOp) {
                        if (videoCore != null) {
                            ((RESHardVideoCore) videoCore).onFrameAvailable();
                        }
                    }
                }
            });
        VirtualDisplay mVirtualDisplay = mediaProjection.createVirtualDisplay(
                "res-display", resCoreParameters.videoWidth,
                resCoreParameters.videoHeight, 1,
                DisplayManager.VIRTUAL_DISPLAY_FLAG_PUBLIC , surface,
                null, null);
        return true;
    }

**Comment by rockscy** [comment]
成功啦 非常感谢大神 还有个小问题.. 怎么同步推音频呢？

**Comment by lakeinchina** [comment]
你没去掉音频的话，会推音频啊

**Comment by rockscy** [comment]
嗯 可以得  是我笔记本的问题.. 太感谢了

**Comment by lakeinchina** [comment]
不客气
