### ISSUE TITLE
配置参数能在预览界面重新进行设置吗

### ISSUE THREAD

**Issue by githubliker** [lakeinchina/librestreaming#66]
你好，我想在预览界面重新配置RESConfig中的参数，当前重新设置后相机界面不显示预览图像，我该怎么处理呢

**Comment by lakeinchina** [comment]
你是怎么重新配置的？
现在如果要重新配置的话，需要重新走一遍生命周期

**Comment by githubliker** [comment]
先进行 resClient.destroy(); 然后重新设置分辨率 码率 推流地址等参数。接着重新resClient.prepare(resConfig)。  画面就一直不动了。没预览数据了

**Comment by lakeinchina** [comment]
destroy之前需要stoppreview，prepare之后再startpreview，surfacetexture先预先存下来

**Comment by githubliker** [comment]
destory之前都没有开始startstreaming呢  所以就不需要stopstreaming了吧

**Comment by lakeinchina** [comment]
对，这些操作都是成对调用的，所有的调用都要在prepare和destroy之间进行

**Comment by githubliker** [comment]
重新配置参数后，相机预览界面不动，但能正常推出流，观看也正常。这大概什么情况导致的呢

**Comment by lakeinchina** [comment]
stoppreview&startpreview了么？

**Comment by githubliker** [comment]
没有重新调用onSurfaceTextureAvailable或者onSurfaceTextureSizeChanged，所以就没有startpriview。需要手动调用一下startpreview吗？

**Comment by lakeinchina** [comment]
前面说了，要手动stoppreview和startpreview
