### ISSUE TITLE
请问如何在视频直播过程中添加一个本地录制功能呢，用于备份直播操作，能给点思路吗

### ISSUE THREAD

**Issue by githubliker** [lakeinchina/librestreaming#68]

**Comment by lakeinchina** [comment]
用android自带的MediaMuxer很容易
把VideoSenderThread和AudioSenderThread里面拿到的编码之后的数据传给MediaMuxer就行了，自动生成到指定mp4
addTrack的时候用MediaEncoder.getOutputFormat()返回的MediaFormat
其他的可以查下资料

**Comment by githubliker** [comment]
好的，我向这个方向试试。谢谢啊

**Comment by xulingchung2016** [comment]
我加了之后，mediaMuxer stop（） 报异常java.lang.IllegalStateException: Can't stop due to wrong state.，录制视频不成功。不知道什么原因

**Comment by sxhdroid** [comment]
> 用android自带的MediaMuxer很容易
> 把VideoSenderThread和AudioSenderThread里面拿到的编码之后的数据传给MediaMuxer就行了，自动生成到指定mp4
> addTrack的时候用MediaEncoder.getOutputFormat()返回的MediaFormat
> 其他的可以查下资料
在VideoSenderThread把数据传递给MediaMuxer生成的mp4码率很低，和预设的不一致是什么原因？
