### ISSUE TITLE
How to change resolution

### ISSUE THREAD

**Issue by dyckster** [lakeinchina/librestreaming#69]
Hi, sorry for a stupid question, but how do you change resolution of the video? I tried resConfig.setTargetVideoSize(new Size(426,240)) but it desorts the preview and stops the app.

**Comment by lakeinchina** [comment]
if you mean just changing default video size at the beginning.it is the right way.
it should be a bug or mediacode doesn`t support the size.Do you hava any log？

**Comment by dyckster** [comment]
@lakeinchina Thanks for reply, I think i just messed up resconfig settings. I figured out that if I restart resClient with different resolution and with rendering mode set to Native window, it will work without problems. Thanks for the great library by the way!

**Comment by lakeinchina** [comment]
If you mean changing videosize during streaming whitout interrupt.this lib can not do that for now.
but I am working on it. branch “hot_reset_videosize” has reSetVideoSize() which can changing videosize without interrupt streaming.it is not fully tested and it only work with hard mode for now.

if you don`t care about interrupt streaming.you can just stopstreaming()&stoppreview()&destroy()，and restart everything. I strongly recommend you to use hard mode .it is more efficient and it can almost set any videosize as your wish which soft mode dosen`t.
rendering mode set to gles should be ok.Store surfacetexture at onSurfaceTextureAvailable and startPreview with it after restart.don`t forgot to stoppreview() before destroy().

**Comment by dyckster** [comment]
@lakeinchina Thanks, I am ok with stopping preview for now :)  Thanks anyway, lookingforward for updates

**Comment by dyckster** [comment]
@lakeinchina I am having some problems with Hard mode. When i try to change resolution using stop-destroy-change-start method app crashes with 

```
 E/BufferQueueProducer: [SurfaceTexture-0-12784-0] connect: BufferQueue has been abandoned
 E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xa16afd08) failed (0xffffffed) (already connected to another API?)
 E/libEGL: eglCreateWindowSurface:464 error 3003 (EGL_BAD_ALLOC)
 E/AndroidRuntime: FATAL EXCEPTION: GLThread
                                                                       Process: com.boomstream.livego, PID: 12784
                                                                       java.lang.RuntimeException: eglCreateWindowSurface,failed:EGL_BAD_ALLOC
                                                                           at me.lake.librestreaming.core.GLHelper.initScreenGL(GLHelper.java:241)
                                                                           at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.initScreenGL(RESHardVideoCore.java:621)
                                                                           at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.handleMessage(RESHardVideoCore.java:364)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
```

Also, when my activity gets created or resolution changes a green screen appears for a moment, how to get rid of it? As far as i checked, it appears after .startPreview().

**Comment by lakeinchina** [comment]
sorry,I have checked the code.it seems like I release surfaceTexture automatically when stopPreview,so it crash when reuse it.
I have solved it. please take “reStartWithResolution(int w, int h)” as an example.

green screen should appear with soft mode.in the beginning arrays filled with zero, it is green color in yuv color space.I don`t mind it before but it has  been changed to black for now.

**Comment by dyckster** [comment]
@lakeinchina Thanks, everything working good, but when i change resolutions using recreating preview method, my preview screen gets the size of resolution set, for example when i choose 240p it becomes realy small. When I use soft mode+Native window mode, everything works well, when I use Hard more and both window modes, it behaves like that.

**Comment by lakeinchina** [comment]
Are you using  the lastest version and the reStartWithResolution()  method？I tested it and it works on my device.

**Comment by dyckster** [comment]
@lakeinchina Woops, didnt see it, used it, works like a charm, though I get weird white bars on resoultion change.

edit: fixed it by removing .setAspectRatio()
