### ISSUE TITLE
请教个视频裁剪问题

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#70]
你好，假如给相机设置的分辨率是640x480，如果想要推流出去的分辨率是640x360，该如何去裁剪呢？

**Comment by lakeinchina** [comment]
你是说推流和预览用不同的分辨率么?

**Comment by jtyang** [comment]
是的，想要推流用16：9的比例，因为手机硬件原因，可能预览使用了640x480的分辨率，所以想要在美颜filter之前先把视频裁剪成640x360的分辨率，然后再做美颜、推流。

**Comment by lakeinchina** [comment]
现在hard模式会自动裁剪的，直接设640*360就行了

**Comment by jtyang** [comment]
是GLHelper的getCamera2DTextureVerticesBuffer(final int directionFlag, final float cropRatio)函数实现的裁剪吗？我再看下，之前好像看了下没起作用。

**Comment by lakeinchina** [comment]
hard模式应该是没问题的，这个功能挺早就加上了。

**Comment by jtyang** [comment]
嗯，是我的问题。不过还有个疑问不知楼主是否有遇到过？MediaFormat的宽高貌似不能随便设置任意数字，我设置为640x360可以，但是设置720x405时编码器configure的时候会拋CodecException异常

**Comment by lakeinchina** [comment]
编码器对分辨率好像有要求，我也没摸清楚，有些会自动给你改成支持的相似的分辨率，一般设成16倍数比较好，405这种奇数的分辨率一般不支持

**Comment by jtyang** [comment]
嗯，thanks！！！

**Comment by skybdemq** [comment]
我想要在soft模式下进行裁剪，设置了RESCoreParameters的videoWidth和videoHeight，但没有画面，请问soft模式下能否实现裁剪效果

**Comment by lakeinchina** [comment]
soft模式如果要裁剪还会涉及到缩放，太耗性能了，所以没有加入

**Comment by skybdemq** [comment]
哦，谢谢。
请教下现在用Hard模式兼容性怎样，是否适合大部分主流机型

**Comment by lakeinchina** [comment]
目前还没发现有什么问题

**Comment by skybdemq** [comment]
好的，谢谢
