### ISSUE TITLE
arm-64的so库在华为X5手机上出错

### ISSUE THREAD

**Issue by githubliker** [lakeinchina/librestreaming#71]
在调用stopstreaming时出错Fatal signal 11 (SIGSEGV), code 1, fault addr 0x27b000004374 in tid 17359 (RESRtmpSender,w)，请问有什么解决思路吗。

**Comment by lakeinchina** [comment]
这是偶现还是必现？

**Comment by githubliker** [comment]
必现的 华为P9手机也不行   SendFCUnpublish(r); SendDeleteStream(r, i); 这两个位置报错

**Comment by lakeinchina** [comment]
华为哪有x5手机？荣耀畅玩5x？荣耀5x

**Comment by githubliker** [comment]
荣耀畅玩5x

**Comment by lakeinchina** [comment]
我远程试了一下，sample没发现崩溃，你是给arm64专门编译了一个so么？armv7直接可以在arm64上用的

**Comment by githubliker** [comment]
确实是自己编译的arm64的库的问题，谢谢你，现在直接用armv7了
