### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#73]
推流使用ijk播放和VLC还有ffplay 播放都正常
但是使用PC网页和手机web播放都没有声音可能是什么原因啊？

**Comment by lakeinchina** [comment]
我没有碰到过这种问题，你的PC和手机web用的是h5播放器？

**Comment by flyminiboy** [comment]
PC是flash 
手机web是H5

**Comment by flyminiboy** [comment]
videoClient.startStreaming(dataCollecter);
rtmpSender.start(coreParameters.rtmpAddr);
audioClient.start(dataCollecter);

这三局代码的顺序不可以改变吗？还是rtmpSender.start(coreParameters.rtmpAddr);这句必须在前面？

**Comment by lakeinchina** [comment]
严格来说rtmpSender.start应该在最前面
