### ISSUE TITLE
数据源

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#76]
我在那个地方可以拿到原始的数据呢（没有编码的数据）

**Comment by lakeinchina** [comment]
从滤镜里取，soft模式是个数组，hard模式是个纹理

**Comment by flyminiboy** [comment]
是滤镜里面
onDraw 里面 targetFrameBuffer 这个吗？
那
FloatBuffer shapeBuffer, FloatBuffer textrueBuffer 这俩个参数是什么？

**Comment by lakeinchina** [comment]
是orignBuff

**Comment by flyminiboy** [comment]
这个是音频的吧？
视频里面没有这个参数
public void onDraw(int cameraTexture, int targetFrameBuffer, FloatBuffer shapeBuffer, FloatBuffer textrueBuffer)

**Comment by lakeinchina** [comment]
soft滤镜是orignBuff，hard滤镜是cameraTexture

**Comment by flyminiboy** [comment]
如果我想对视频数据进行旋转操作，是操作原始数据，还是编码以后的数据呢。

**Comment by lakeinchina** [comment]
resConfig.setFrontCameraDirectionMode((frontDirection == 90 ? RESConfig.DirectionMode.FLAG_DIRECTION_ROATATION_270 : RESConfig.DirectionMode.FLAG_DIRECTION_ROATATION_90) | RESConfig.DirectionMode.FLAG_DIRECTION_FLIP_HORIZONTAL);
            resConfig.setBackCameraDirectionMode((backDirection == 90 ? RESConfig.DirectionMode.FLAG_DIRECTION_ROATATION_90 : RESConfig.DirectionMode.FLAG_DIRECTION_ROATATION_270));

想这样配置旋转就行了

**Comment by flyminiboy** [comment]
我想实现动态的那个旋转，
我想可不可以通过一个滤镜实现呢，通过传递的一个旋转角度，然后对数据进行旋转。hard模式

**Comment by lakeinchina** [comment]
可以转，但是现在不能改变分辨率，比如横屏不能变成竖屏
