### ISSUE TITLE
librtmp流断开问题

### ISSUE THREAD

**Issue by zcg121314** [lakeinchina/librestreaming#79]
LibRTMP.NDK：WriteN，RTMP发送错误9（140字节）
LibRTMP.NDK：WriteN，RTMP发送错误9（140字节）
出现这个流就断了

**Comment by lakeinchina** [comment]
9就是tcp连接已经断了，这可能是太多情况导致，你可以在多种网络环境测试一下

**Comment by zcg121314** [comment]
局域网测也断3-4个小时左右才出
