### ISSUE TITLE
Compiling x86 , x64

### ISSUE THREAD

**Issue by developeralp** [lakeinchina/librestreaming#80]
Hi ,

Thanks for this great library.

How can i compile native libraries to x86 , x64 and other architectures ?

**Comment by lakeinchina** [comment]
Modify Application.mk,add x86 , arm64-v8a etc in APP_ABI.
Please note that other CPU architecture is not tested.
because there are few x86 devices,and arm64 is compatible with arm32.

**Comment by developeralp** [comment]
Thanks for your quick reply , i will try that as you said.

**Comment by PreDeToR** [comment]
Hi Guys

Once I have this module/system checked out,made the changes above.
How do I force it to compile the new library files?

Regards
Danie
