### ISSUE TITLE
推流的同时推一个本地视频出去

### ISSUE THREAD

**Issue by flyminiboy** [lakeinchina/librestreaming#81]
麻烦指点一个思路，谢谢！

**Comment by lakeinchina** [comment]
推流的同时推一个本地视频是啥意思

**Comment by flyminiboy** [comment]
类似加图片水印那样，在一个指定区域加载一个本地视频也一起推出去

**Comment by lakeinchina** [comment]
本地视频的播放要用另外的播放器做，还要从播放器拿到视频帧，通过滤镜绘制到流里

**Comment by flyminiboy** [comment]
我可以先对本地视频进行解码，拿到视频帧，然后绘制到流里面，然后再一起推出去吗？

**Comment by lakeinchina** [comment]
是这个意思，只要能拿到视频每一帧，然后就像绘制水印一样通过滤镜绘制到流里就行了，拿视频帧需要播放器来支持，我不可能在一个推流库里内置一个播放器。
建议上面都用hard模式来做

**Comment by flyminiboy** [comment]
解码以后得到的数据是YUV420 的，我可以直接使用这个数据进行绘制吗？还是我需要先把YUV420的数据转成bitmap

**Comment by lakeinchina** [comment]
手动yuv转argb很慢，如果视频不大可以考虑，最好能直接拿到argb的格式，可以一句话转换成gl纹理。
如果拿不到，那就有点麻烦，可以参考GLESRender.java那样直接渲染nv21格式的数据。

**Comment by flyminiboy** [comment]
好的  多谢指点！
