### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by junknown** [lakeinchina/librestreaming#82]
Hi, 
trying your library i noticed thers's no way to follow screen rotation. 
How can i accomplish that? 
The example activity is blocked on one choosed configuration, that is fine, but texture surface rotates anyway and video results to be rotated by 90
Thanks

**Comment by lakeinchina** [comment]
do you mean rotate video during streaming？

**Comment by junknown** [comment]
Yes, without stopping and restarting the rtmp connection

**Comment by lakeinchina** [comment]
in hot_reset_videosize branch,it can reset video parameter without reset rtmp streaming。
it can`t hot rotate video for now because i did`t update the related rotation property.bug improve it to support hot rotate should be easy

**Comment by junknown** [comment]
Thanks. i'll give it a look.
