### ISSUE TITLE
网络切换后推流中断

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#83]
从移动网络切换到4G, 推流就直接中断了, 尝试过在网络变更后重启, 但是没能生效, 请问该如何优化这个场景的操作呢.

**Comment by lakeinchina** [comment]
没能生效是什么意思？onOpenConnectionResult返回值是什么？

**Comment by hike2008** [comment]
结果是onOpenConnectionResult结果是 1

**Comment by hike2008** [comment]
我是定义了一个 NetStatusReceiver, 在推流界面进行注册, 当网络变化了, 先mRESClient.stop(); 然后 mRESClient.start();的

**Comment by lakeinchina** [comment]
可能你的网络变化之后重启是在网络还没连接的时候重启的，然后连接失败。
onOpenConnectionResult结果是1就是连接失败，可以延迟几秒再重启，一直循环到成功为止，demo里面连接失败不会自动重启了。
如果已经开始推流，网络变化onWriteError也会有回调，demo里面会自动重启。

像这样
    `

@Override
    public void onOpenConnectionResult(int i) {
        if (i != 0) {
            if (isStarted) {
                resClient.stopStreaming();
                isStarted = false;
                restartHandler.sendEmptyMessageDelayed(MSG_CHECKSPEED_RESTART, 4000);
            }
        } else {
            UIUtils.showToast(Activity.this, "连接成功,开始直播");
        }
    }

```
@Override
public void onWriteError(int i) {
    if (i == 9) {
        if (isStarted) {
            resClient.stopStreaming();
            isStarted = false;
            restartHandler.sendEmptyMessageDelayed(MSG_CHECKSPEED_RESTART, 2000);
        }
    }
}

    class RestartHandler extends Handler {
    @Override
    public void handleMessage(Message msg) {
        switch (msg.what) {
            case MSG_CHECKSPEED_RESTART:
                if (!isStarted) {
                    resClient.startStreaming();
                    isStarted = true;
                }
                break;
        }
    ｝
```

`

请用最新版本，onwriteerror回调参数修改过，现在返回的是tcp的errno

**Comment by hike2008** [comment]
好的, 谢谢, 我抽空验证一下最新版本, 然后再更新.

**Comment by hike2008** [comment]
另外, 根据网络状态, 调整分辨率和码流的分支, 目前是可以用的么

**Comment by lakeinchina** [comment]
主分支能动态调码率，hot_reset_videosize分支能动态重设分辨率

**Comment by hike2008** [comment]
好的, 谢谢
