### ISSUE TITLE
Passing tcUrl,pageUrl,swfUrl elements on startStreaming()

### ISSUE THREAD

**Issue by developeralp** [lakeinchina/librestreaming#85]
Hello , i'm passing some values to rtmp server via pageUrl or swfUrl..

How can i change that in librestreaming ?

**Comment by lakeinchina** [comment]
Sorry,It can`t  set tcUrl,pageUrl,swfUrl for now,if you want to,you have to set it by changing jni code.
like:
r->Link.pageUrl
r->Link.swfUrl 
r->Link.tcUrl
in rtmp.c

**Comment by developeralp** [comment]
Thanks @lakeinchina i will try that.
