### ISSUE TITLE
视频编码的BaseLine如何改为Main级别呢, 目前是Constrained Baseline

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#86]

**Comment by hike2008** [comment]
videoFormat.setInteger(MediaFormat.KEY_PROFILE, MediaCodecInfo.CodecProfileLevel.AVCProfileMain);

除了修改这个, 还有 其他的需要修改么

**Comment by lakeinchina** [comment]
这个东西在大部分手机上是没有效果的，谷歌在底层强行把这个又改成了baseline
https://code.google.com/p/android/issues/detail?id=215639

**Comment by hike2008** [comment]
好吧, 涨姿势了又, 

https://code.google.com/p/android/issues/detail?id=163580

这个issue, 是不是说未来会修复这个问题

**Comment by hike2008** [comment]
无比感谢

**Comment by lakeinchina** [comment]
7.0里面看起来已经修复了http://androidxref.com/7.0.0_r1/xref/frameworks/av/media/libstagefright/ACodec.cpp

**Comment by hike2008** [comment]
嗯
