### ISSUE TITLE
Oppo r7plus相机预览出现频繁卡顿

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#88]
hi，今天偶然发现这个bug，不知道是不是机型适配有啥问题。
机型：oppo r7plus
系统：coloros v2.1  （android 5.1.1）

我再跟进下，有结果的话再发出来。

**Comment by lakeinchina** [comment]
我远程测试了一下，debug显示的帧率看起来正常，这个是必现还是偶现？

**Comment by jtyang** [comment]
偶现，用了另一台oppo F1f测试也有类似情况，但其他品牌手机又不会，他不是一直卡，而是流畅一会儿，然后停顿一两秒，这个出现的频率也不一定。
