### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jtyang** [lakeinchina/librestreaming#9]
1.rtmp在x86机器关闭的时候会崩溃；
2.美颜在低端机器还是比较卡。（硬模式）

**Comment by lakeinchina** [comment]
x86能成功推流吗？关闭有崩溃日志么？
我把hard磨皮优化了一下，把非肤色排除了，脸大的有点劣势。。

**Comment by jtyang** [comment]
@lakeinchina  x86能推流成功，就是关闭的时候底层c代码崩溃，日志暂时没有；
另外请教下美颜这块：因为项目原因，想改用gpuimage那个库来做美颜，但是如果直接把现在的BaseHardVideoFilter改成GPUImageFilter，不知道是不是改的姿势不对，改完后一开美颜画面就卡死不动了，请问下你知道是为啥吗？Thanks！

**Comment by lakeinchina** [comment]
你怎么拿过来的。。代码没有这我咋知道为啥，直接拿过来肯定是不行的。。sample里面的SobelEdgeDetectionHardVideoFilter-Base3x3SamplingHardVideoFilter是我从GPUimage改过来的

**Comment by jtyang** [comment]
@lakeinchina  嗯嗯，看了下代码，貌似是不能直接把BaseHardVideoFilter替换成GPUImageFilter，请问下如果想把gpuimage库的GPUImageBilateralFilter滤镜移过来，是直接写个类继承OriginalHardVideoFilter，然后替换里面的vertexShader_filter、fragmentshader_filter还是要继承BaseHardVideoFilter，去改opengl的实现？不好意思啊，对opengl这块不熟，还望指点下！多谢！

**Comment by lakeinchina** [comment]
一般情况下只需要继承OriginalHardVideoFilter然后传个shader就行了比如FishEyeFilterHard。
如果需要传常量到shader里面只需要在onPreDraw里面设值比如SkinBlurHardVideoFilter。

如果你会gles的话，可以直接用BaseHardVideoFilter，需要在onInit里面进行初始化操作比如创建program，onDraw里面需要把cameraTexture纹理绘制到targetFrameBuffer帧缓存上，onDestroy里面进行销毁操作。

其实和gpuimage原理没多少区别，只是它把每一步分的特别细，我分的比较粗，移植其实特别简单。
我不知道你的代码是什么版本，最好经常更新一下，为了支持组合滤镜，hard滤镜结构我改过一点。之后应该会稳定下来。
我其实对如何设计gl滤镜结构这块也没多少经验，有什么建议可以跟我提。
另外，gpuimage好像没有美颜滤镜吧？

**Comment by jtyang** [comment]
嗯，多谢，我再研究下，现在主要ios端用了gpuimage的一些滤镜，android端也想拿过来看下。
