### ISSUE TITLE
推流分辨率, fps, VideoBufferQueueNum等参数的匹配关系

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#90]
使用720 \* 480 的分辨率, 推流比较正常;
一旦切换为 480p(852 \* 480),  就会出现花屏, 掉帧现象, 而且移动时, 尤为明显;

所以想问下, 是否这几个参数有一些对应关系:
        resConfig.setTargetVideoSize(new Size(720, 480));
        resConfig.setBitRate(1000 \* 1024);
        resConfig.setVideoFPS(30);
        resConfig.setVideoBufferQueueNum();

比如: 当 设置resConfig.setTargetVideoSize(new Size(852, 480)); 时, bitrate肯定要更大, 
那是否应该还相应调整  resConfig.setVideoBufferQueueNum(); 为更大的值

**Comment by lakeinchina** [comment]
resConfig.setVideoBufferQueueNum()不用修改。这个是给网络波动留的缓冲的大小
主要是分辨率和码率要对应，码率越高画面移动越不花

**Comment by hike2008** [comment]
好的, 谢谢 , setVideoBufferQueueNum, 是否可以与播放的追赶缓冲时间一致? 这样是否有助于直播的延迟追赶

**Comment by lakeinchina** [comment]
这个对延迟没帮助，只是为了在网络波动的时候不至于丢包，如果这个缓冲一直满，那基本上就是在丢包了

**Comment by hike2008** [comment]
好的, 谢谢
