### ISSUE TITLE
推流结束生成回放的flv格式时长不准确

### ISSUE THREAD

**Issue by hike2008** [lakeinchina/librestreaming#91]
使用百度金山的也试过, flv格式时间戳比较准备, 不知道是不是需要设置什么参数 , 以使得录制出来的flv时间戳比较准确.

**Comment by lakeinchina** [comment]
谁生成的回放flv？

**Comment by hike2008** [comment]
流媒体服务器自动生成的

**Comment by flyminiboy** [comment]
修改一下时间戳好像就好了
叫时间戳从0开始计时

**Comment by hike2008** [comment]
怎么修改呢

**Comment by lakeinchina** [comment]
这个可能和流媒体服务器有关，我这测了一下没发现问题。如果要从零开始，把AudioSenderThread和VideoSenderThread里面sendRealData((eInfo.presentationTimeUs / 1000), realData);这一句换成sendRealData((eInfo.presentationTimeUs / 1000)-startTime, realData);

**Comment by hike2008** [comment]
确实 时间戳从0 开始就好了, 拖动以及总时长都是ok的.

**Comment by hike2008** [comment]
正在测试较长时间的时长及拖动

**Comment by hike2008** [comment]
时间比较长的话还是不行,  不准确, 推流推了47分钟32秒, 但是读取的总时长确实1小时13分钟54秒

**Comment by hike2008** [comment]
是因为喂的时间戳是int型导致的么

**Comment by lakeinchina** [comment]
时间戳就是32位的，我也比较奇怪，视频播放速度是对的，但是显示的时间快进了

**Comment by hike2008** [comment]
那会是缓冲区时间叠加导致的么

**Comment by hike2008** [comment]
不知道对于时长不准确目前有什么眉目么, 或者 建议的排查方向  @lakeinchina

**Comment by lakeinchina** [comment]
@hike2008  我测了一下，只传音频的话好像是对的，这个问题可能和视频时间戳有关。
你可以把AudioSenderThread上次的时间戳记下来，然后VideoSenderThread发视频的时候用这个时间戳，我试了一下短时间内准确了。
还不清楚具体原因

**Comment by hike2008** [comment]
暂时通过后台转码方式解决了, 但是非合理处理方式吧, 感觉
