### ISSUE TITLE
errno==9,restarting

### ISSUE THREAD

**Issue by artsector** [lakeinchina/librestreaming#92]
This error vanishes if at all turn off the audio

And thank you for work and support )

**Comment by artsector** [comment]
Error occurs at all devices available
(Samsung, Sony, MI) Android> 4.4.2

**Comment by lakeinchina** [comment]
you mean “errno==9,restarting” continuous appears after you press start button？
and what do you mean “turn off the audio”？

**Comment by artsector** [comment]
> you mean “errno==9,restarting” continuous appears after you press start button？

yes

> and what do you mean “turn off the audio”？
1. you have mute function in BaseActivity, i use it
2. i can disable output 
   //dataCollecter.collect(resFlvData, RESRtmpSender.FROM_AUDIO);

this problem with incorrect dts, when we send audio thread 

now i try to fix it by my self, and if i solve problem then push to repo

**Comment by artsector** [comment]
resolved #94
