### ISSUE TITLE
librtmp changing pageurl error 

### ISSUE THREAD

**Issue by developeralp** [lakeinchina/librestreaming#95]
Hello all,

I asked _how to pass pageUrl,tcUrl on startStreaming()_ last week.

lakeinchina said _to change pageUrl you can change r->Link.pageUrl on rtmp.c_

I'm not good at c and c++.. when i set r->Link.pageUrl in rtmp.c , on RTMP_SetupURL method 

with this ;

`r->Link.pageUrl = "MY_PAGE_URL";`

But ndk-build gives me that error ;

```

error: assigning to 'AVal'
      (aka 'struct AVal') from incompatible type 'char [12]'
  r->Link.pageUrl = "MY_PAGE_URL";
```

How can i solve this problem ?

**Comment by developeralp** [comment]
solution : not use pageurl , use different method for authentication :D

**Comment by lakeinchina** [comment]
the type of "r->Link.pageUrl" is  a struct of AVal , with a char\* and the length of it.
  typedef struct AVal
  {
    char *av_val;
    int av_len;
  } AVal;

use it like this:
const AVal RTMP_LibResFlashVer =
        { (char *)"abc", 3 };

**Comment by developeralp** [comment]
Thanks @lakeinchina i will try this.
