### ISSUE TITLE
关于鉴权的问题

### ISSUE THREAD

**Issue by daweibayu** [lakeinchina/librestreaming#96]
最近刚接触直播相关的东西，对整个流程并不是很清楚。
有几个问题想问一下：
1、librestreaming 是否支持推拉流的鉴权？用流密钥
2、关于鉴权，具体的流程是什么？我看阿里云、七牛等都有鉴权逻辑，而且 OBS 中也是支持的，所以感觉应该是有个标准协议的。但是看 RESConfig.java 中并没有相关的设置。而且我这边 google 搜了一些关键字，并没有找到想要的，如果可以的话可以告诉我一下大概的流程，或者贴一些相关的链接也行。谢谢。

**Comment by lakeinchina** [comment]
这个只有推流，没有播放。而且我没有鉴权的需求，所以对此也没有研究，不太清楚是否在url中加入鉴权参赛就行了

**Comment by daweibayu** [comment]
恩恩，了解，谢谢。
