### ISSUE TITLE
Reg: Only Audio Streaming

### ISSUE THREAD

**Issue by Kishore1224** [lakeinchina/librestreaming#99]
Hi 

Very Good Scripting.. Thanks for that..
I want to know that.. Just i want to stream only Audio with this Lib.

Can you tell me same way .....

**Comment by lakeinchina** [comment]
it does`t have this configuration.
but you can just delete "videoClient.startStreaming(dataCollecter);" and "videoClient.stopStreaming();" in RESClient.java to achieve this purpose
